export const wordList = [
    { word: "divide… into…", meaning: "把…分成…(divide)" },
    { word: "by the time", meaning: "到…为止(time)" },
    { word: "make sure", meaning: "确保(sure)" },
    { word: "have a hard time doing sth.", meaning: "做…有困难(time)" },
    { word: "prepare for", meaning: "为…做准备(prepare)" },
    { word: "make great contributions to sth.", meaning: "对…做出巨大贡献(contribution)" },
    { word: "had better (not) do sth.", meaning: "最好(不)做…(better)" },
    { word: "avoid doing sth.", meaning: "避免做…(avoid)" },
    { word: "be fond of doing sth.", meaning: "喜欢做…(fond)" },
    { word: "in person", meaning: "亲自(person)" },
    { word: "stay awake", meaning: "保持清醒(awake)" },
    { word: "make room for", meaning: "为…腾出空间(room)" },
    { word: "give sb. some advice on", meaning: "给某人关于…的一些建议(advice)" },
    { word: "go to bed", meaning: "上床睡觉(bed)" },
    { word: "remember to do sth.", meaning: "记得要做…(remember)" },
    { word: "remember doing sth.", meaning: "记得做过…(remember)" },
    { word: "would you like to do sth.", meaning: "你愿意做…吗(would)" },
    { word: "be so interested in", meaning: "对…如此感兴趣(interested)" },
    { word: "improve living standards", meaning: "提升生活水平(standard)" },
    { word: "take pride in", meaning: "以…为傲(pride)" },
    { word: "be proud of", meaning: "以…为傲(proud)" },
    { word: "enjoy doing sth.", meaning: "喜欢做…(enjoy)" },
    { word: "make comments on", meaning: "就…做评价(comment)" },
    { word: "self-introduction", meaning: "自我介绍(introduction)" },
    { word: "take place", meaning: "发生(place)" },
    { word: "take the place of", meaning: "取代(place)" },
    { word: "get rid of", meaning: "去除，摆脱(rid)" },
    { word: "divide into", meaning: "分为(divide)" },
    { word: "put… into action", meaning: "把…付诸实践(action)" },
    { word: "put… into practice", meaning: "把…付诸实践(practice)" },
    { word: "attract one's attention", meaning: "吸引某人的注意力(attract)" },
    { word: "draw one's attention", meaning: "吸引某人的注意力(draw)" },
    { word: "catch one's attention", meaning: "吸引某人的注意力(catch)" },
    { word: "pay attention to doing sth.", meaning: "注意做…(attention)" },
    { word: "tend to do sth.", meaning: "往往会做…(tend)" },
    { word: "achieve one's dream", meaning: "实现某人的梦想(achieve)" },
    { word: "make one's dream come true", meaning: "实现某人的梦想(come)" },
    { word: "out of", meaning: "出自，缺少，脱离(out)" },
    { word: "in addition to doing sth.", meaning: "除了做…之外还有(addition)" },
    { word: "at all", meaning: "根本，究竟(all)" },
    { word: "a lack of", meaning: "缺乏(lack->n.)" },
    { word: "lacking in", meaning: "缺乏(lack->adj.)" },
    { word: "be caught in the rain", meaning: "淋雨(catch)" },
    { word: "much to one's surprise", meaning: "令某人非常惊讶的是(much)" },
    { word: "different kinds of", meaning: "不同种类的(kind)" },
    { word: "sing high praise for", meaning: "高度赞扬(praise)" },
    { word: "play an important role in", meaning: "在…中扮演重要角色(role)" },
    { word: "play an important part in", meaning: "在…方面起重要作用(part)" },
    { word: "sb. be devoted to doing sth.", meaning: "某人投身于做…(devoted)" },
    { word: "devotion to doing sth.", meaning: "对做…的奉献(devotion)" },
    { word: "manage to do sth.", meaning: "设法做…(manage)" },
    { word: "a variety of", meaning: "各种各样的(variety)" },
    { word: "be likely to do sth.", meaning: "很可能会做…(likely to)" },
    { word: "it is likely that", meaning: "很可能…(likely that)" },
    { word: "whether… or…", meaning: "(无论)是…还是…(whether)" },
    { word: "whether or not", meaning: "(无论)是否(whether)" },
    { word: "whether or no", meaning: "无论如何(whether)" },
    { word: "blow away", meaning: "吹走，深深打动(blow)" },
    { word: "bring down", meaning: "降低，打倒(bring)" },
    { word: "put into action", meaning: "付诸行动(action)" },
    { word: "put into practice", meaning: "付诸行动(practice)" },
    { word: "keep in touch with", meaning: "与…保持联系(touch)" },
    { word: "one day", meaning: "总有一天(day)" },
    { word: "by all means", meaning: "当然，无论如何，用一切手段(all)" },
    { word: "by any means", meaning: "通过任何方式，无论如何(any)" },
    { word: "by no means", meaning: "决不，绝不(no)" },
    { word: "by means of", meaning: "通过/依靠…(方法)(means)" },
    { word: "be to blame for sth.", meaning: "应受谴责，应负责任(blame)" },
    { word: "blame sb. for sth.", meaning: "因…责怪某人(blame)" },
    { word: "blame on", meaning: "归咎于…(blame)" },
    { word: "be different from", meaning: "与…不同(different)" },
    { word: "the same as", meaning: "与…相同(same)" },
    { word: "be similar to sth.", meaning: "与…相似(similar)" },
    { word: "try one's best", meaning: "尽某人最大努力(try)" },
    { word: "make the best of", meaning: "尽力而为，充分利用(make)" },
    { word: "all the best", meaning: "万事如意，一切顺利(all)" },
    { word: "on condition that", meaning: "条件是(condition)" },
    { word: "be in good condition", meaning: "状态良好(condition)" },
    { word: "be in bad condition", meaning: "状态不佳(condition)" },
    { word: "enjoy yourself", meaning: "祝你玩得开心，请自便(enjoy)" },
    { word: "enjoy oneself", meaning: "玩得开心(enjoy)" },
    { word: "make oneself at home", meaning: "别客气(home)" },
    { word: "help yourself to doing sth.", meaning: "请自便…(help)" },
    { word: "by oneself", meaning: "独自，靠某人自己(by)" },
    { word: "put off", meaning: "推迟(put)" },
    { word: "complain about", meaning: "抱怨(complain)" },
    { word: "had fun (in) doing sth.", meaning: "做…很开心(fun)" },
    { word: "set a good example for", meaning: "为…树立好榜样(example)" },
    { word: "set good examples for", meaning: "为…树立好榜样(examples)" },
    { word: "be far away from", meaning: "远离，距…远(far)" },
    { word: "on time", meaning: "准时(time)" },
    { word: "in time", meaning: "及时(time)" },
    { word: "spend time doing sth.", meaning: "花时间做…(spend)" },
    { word: "spend time on", meaning: "在…上花时间(spend)" },
    { word: "come to oneself", meaning: "苏醒(come)" },
    { word: "get lost", meaning: "迷路(lost)" },
    { word: "be strict with sb.", meaning: "对…要求严格(strict)" },
    { word: "so far", meaning: "到目前为止，到这种程度(far)" },
    { word: "help sb. with", meaning: "帮助某人解决某种问题(help)" },
    { word: "help sb. do sth.", meaning: "帮助某人做…(help)" },
    { word: "with one's help", meaning: "在某人的帮助下(help)" },
    { word: "with the help of sb.", meaning: "在…的帮助下(the help)" },
    { word: "mind doing sth.", meaning: "介意做…(mind)" },
    { word: "result in", meaning: "导致…(result)" },
    { word: "result from", meaning: "由…导致(result)" },
    { word: "try to do sth.", meaning: "尽力做…(try)" },
    { word: "try doing sth.", meaning: "尝试做…(try)" },
    { word: "push in", meaning: "插队(push)" },
    { word: "cut in", meaning: "插队\\嘴\\入(cut)" },
    { word: "stop to do sth.", meaning: "停下…去做…(stop)" },
    { word: "stop doing sth.", meaning: "停下(正在做的…)(stop)" },
    { word: "in order that", meaning: "为了(+从句)(order)" },
    { word: "in order to do sth.", meaning: "为了(+do)(order)" },
    { word: "search for", meaning: "寻找(search)" },
    { word: "look for", meaning: "寻找(look)" },
    { word: "waste time doing sth.", meaning: "浪费时间做…(waste)" },
    { word: "waste time on sth.", meaning: "在…浪费时间(waste)" },
    { word: "lose touch with sb.", meaning: "与…失联(touch)" },
    { word: "put on", meaning: "穿上(put)" },
    { word: "apply for", meaning: "申请(apply)" },
    { word: "be seriously hurt", meaning: "受重伤(hurt)" },
    { word: "at once", meaning: "立刻(at)" },
    { word: "right now", meaning: "立刻(now)" },
    { word: "right away", meaning: "立刻(away)" },
    { word: "fall in love with sb.", meaning: "爱上…(fall)" },
    { word: "fall in love", meaning: "坠入爱河(fall)" },
    { word: "be in love with sb.", meaning: "爱上…(be)" },
    { word: "put emphasis on", meaning: "强调…(put)" },
    { word: "attach important to sth.", meaning: "重视…(important)" },
    { word: "turn up", meaning: "出现，调高(音量…)(turn)" },
    { word: "turn down", meaning: "拒绝，调低(音量…)(turn)" },
    { word: "take care of", meaning: "照顾，支付(尤指替他人)(care)" },
    { word: "a stark contrast to sth.", meaning: "与…形成鲜明对比(contrast)" },
    { word: "make a good impression on", meaning: "给…留下好印象(impression)" },
    { word: "not… but…", meaning: "不是…而是(not)" },
    { word: "put away", meaning: "收起，储存，将…送进(监狱…)(put)" },
    { word: "be eager to do sth.", meaning: "渴望做…(eager)" },
    { word: "around the world", meaning: "全世界(around)" },
    { word: "all over the world", meaning: "全世界(all)" },
    { word: "decide to do sth.", meaning: "决定做…(decide)" },
    { word: "in front of", meaning: "在(外部的)…前面(front)" },
    { word: "in the front of", meaning: "在…(内部的)前面(front)" },
    { word: "it takes sb. 时间/金钱 to do sth.", meaning: "某人花费多长时间/多少钱做…(take)" },
    { word: "in other words", meaning: "换言之(words)" },
    { word: "have the potential to do sth.", meaning: "有潜力做…(have)" },
    { word: "live a(n) [adj.] life", meaning: "过着…的生活(life)" },
    { word: "be inspired by", meaning: "被…启发/鼓舞(be)" },
    { word: "have nothing to do with", meaning: "与…无关(nothing)" },
    { word: "be severely punished", meaning: "受到严厉惩罚(punished)" },
    { word: "make full use of", meaning: "充分利用(use)" },
    { word: "have a good command of", meaning: "精通…(command)" },
    { word: "be ready to do sth.", meaning: "准备/愿意/乐意做…(ready)" },
    { word: "arouse the awareness of", meaning: "唤起对…的意识(arouse)" },
    { word: "have a picnic", meaning: "去野餐(have)" },
    { word: "offer sb. sth.", meaning: "提供某人…(offer)" },
    { word: "offer sth. to sb.", meaning: "提供…给某人(offer)" },
    { word: "help sb. (to) do sth.", meaning: "帮助某人做…(help)" },
    { word: "intend sb.to do sth.", meaning: "打算要某人做…(intend)" },
    { word: "invite sb.to do sth.", meaning: "邀请某人做…(invite)" },
    { word: "provide sb. with sth.", meaning: "提供某人…(provide)" },
    { word: "provide sth. for sb.", meaning: "提供…给某人(provide)" },
    { word: "hear of", meaning: "听说(hear)" },
    { word: "start to do sth.", meaning: "开始做…(start)" },
    { word: "such as", meaning: "例如(such)" },
    { word: "from time to time", meaning: "时不时(time)" },
    { word: "be of great importance", meaning: "非常重要(importance)" },
    { word: "to begin with", meaning: "首先(begin)" },
    { word: "take up one's spare time", meaning: "占用某人的空闲时间(take)" },
    { word: "in addition", meaning: "此外(addition)" },
    { word: "make a wise choice of", meaning: "做一个明智的…的选择(choice)" },
    { word: "set up", meaning: "建立，设置，安排(set)" },
    { word: "encourage sb. to do sth.", meaning: "鼓励某人做…(encourage)" },
    { word: "focus on", meaning: "专注/集中/聚焦/侧重于(focus)" },
    { word: "have… in common", meaning: "在…有共同点(common)" },
    { word: "force sb. to do sth.", meaning: "强迫某人做…(force)" },
    { word: "up and down", meaning: "上上下下(and)" },
    { word: "jump up and down", meaning: "跳上跳下(and)" },
    { word: "my suggestions are as follows", meaning: "我的建议如下(suggestion)" },
    { word: "aim to do sth.", meaning: "打算做…(aim)" },
    { word: "ask to do sth.", meaning: "要求做…(ask)" },
    { word: "finish doing sth.", meaning: "完成做…(finish)" },
    { word: "give up doing sth.", meaning: "放弃做…(give)" },
    { word: "forbid doing sth.", meaning: "禁止做…(forbid)" },
    { word: "miss doing sth.", meaning: "错过做…(miss)" },
    { word: "pardon doing sth.", meaning: "原谅做…(pardon)" },
    { word: "refuse to do sth.", meaning: "拒绝做…(refuse)" },
    { word: "offer to do sth.", meaning: "主动提出做…(offer)" },
    { word: "expect to do sth.", meaning: "期望做…(expect)" },
    { word: "wish to do sth.", meaning: "希望做…(wish)" },
    { word: "hope to do sth.", meaning: "希望做…(hope)" },
    { word: "permit doing sth.", meaning: "允许做…(permit)" },
    { word: "practise doing sth.", meaning: "练习做…(practise)" },
    { word: "prevent doing sth.", meaning: "阻止做…(prevent)" },
    { word: "want to do sth.", meaning: "想要做…(want)" },
    { word: "consider doing sth.", meaning: "考虑做…(consider)" },
    { word: "delay doing sth.", meaning: "推迟做…(delay)" },
    { word: "there is no denying", meaning: "不可否认(deny)" },
    { word: "deny doing sth.", meaning: "否认做…(deny)" },
    { word: "keep doing sth.", meaning: "继续做…(keep)" },
    { word: "long to do sth.", meaning: "渴望做…(long)" },
    { word: "fear to do sth.", meaning: "害怕做…(fear)" },
    { word: "beg to do sth.", meaning: "请求做…(beg)" },
    { word: "struggle to do sth.", meaning: "努力做…(struggle)" },
    { word: "dare to do sth.", meaning: "敢于做…(dare)" },
    { word: "expect to do sth.", meaning: "期望做…(expect)" },
    { word: "force sb.to do sth.", meaning: "强迫某人做…(force)" },
    { word: "expect sb.to do sth.", meaning: "期望某人做…(expect)" },
    { word: "want sb. to do sth", meaning: "想要某人做…(want)" },
    { word: "warn sb. to do sth.", meaning: "警告某人做…(warn)" },
    { word: "would rather do sth.", meaning: "宁愿做…(would)" },
    { word: "may as well do sth.", meaning: "不妨做…(may)" },
    { word: "might as well do sth.", meaning: "不妨做…(might)" },
    { word: "can't help but do sth.", meaning: "忍不住做…(help)" },
    { word: "do nothing but do", meaning: "除了做…之外…也不做(but)" },
    { word: "have nothing to do but do", meaning: "除了做…之外别无选择(but)" },
    { word: "take to doing sth.", meaning: "逐渐习惯做…(take)" },
    { word: "sth. need doing", meaning: "…需要被做(need)" },
    { word: "sth. want doing", meaning: "…需要被做(want)" },
    { word: "sth. require doing", meaning: "…需要被做(require)" },
    { word: "sth. be worth doing", meaning: "…值得被做(worth)" },
    { word: "demand to do sth.", meaning: "要求做…(demand)" },
    { word: "happen to do sth.", meaning: "碰巧做…(happen)" },
    { word: "hesitate to do sth.", meaning: "犹豫做…(hesitate)" },
    { word: "plan to do sth.", meaning: "计划做…(plan)" },
    { word: "wait to do sth.", meaning: "等待做…(wait)" },
    { word: "be worthy of doing", meaning: "值得做…(worthy)" },
    { word: "admit doing sth.", meaning: "承认做…(admit)" },
    { word: "advise doing sth.", meaning: "建议做…(advise)" },
    { word: "allow doing sth.", meaning: "允许做…(allow)" },
    { word: "appreciate doing sth.", meaning: "感激做…(appreciate)" },
    { word: "can't help doing sth.", meaning: "忍不住做…(help)" },
    { word: "mention doing sth.", meaning: "提及做…(mention)" },
    { word: "mind doing sth.", meaning: "介意做…(mind)" },
    { word: "discuss doing sth.", meaning: "谈论做…(discuss)" },
    { word: "dislike doing sth.", meaning: "讨厌做…(dislike)" },
    { word: "be accustomed to doing sth.", meaning: "习惯做…(accustom)" },
    { word: "be opposed to doing sth.", meaning: "反对做…(oppose)" },
    { word: "confess to doing sth.", meaning: "承认做了…(confess)" },
    { word: "look forward to doing sth.", meaning: "期待做…(look)" },
    { word: "enjoy doing sth.", meaning: "喜欢做…(enjoy)" },
    { word: "escape doing sth.", meaning: "逃脱做…(escape)" },
    { word: "excuse doing sth.", meaning: "借口做…(excuse)" },
    { word: "learn to do sth.", meaning: "学会做…(learn)" },
    { word: "care to do sth.", meaning: "想要做…(care)" },
    { word: "afford to do sth.", meaning: "负担得起做…(afford)" },
    { word: "explain doing sth.", meaning: "解释做…(explain)" },
    { word: "fancy doing sth.", meaning: "设想做…(fancy)" },
    { word: "prohibit doing sth.", meaning: "禁止做…(prohibit)" },
    { word: "put off doing sth.", meaning: "推迟做…(put)" },
    { word: "agree to do sth.", meaning: "同意做…(agree)" },
    { word: "choose to do sth.", meaning: "选择/决定做…(choose)" },
    { word: "pretend to do sth.", meaning: "假装做…(pretend)" },
    { word: "promise to do sth.", meaning: "答应做…(promise)" },
    { word: "recall doing sth.", meaning: "回忆起做了…(recall)" },
    { word: "report doing sth.", meaning: "报告做了…(report)" },
    { word: "be reported to do sth.", meaning: "据报告做了…(report)" },
    { word: "resist doing sth.", meaning: "拒绝做…(resist)" },
    { word: "risk doing sth.", meaning: "冒险做…(risk)" },
    { word: "suggest doing sth.", meaning: "建议做…(suggest)" },
    { word: "understand doing sth.", meaning: "理解做…(understand)" },
    { word: "determine to do sth.", meaning: "决定做…(determine)" },
    { word: "mean to do sth.", meaning: "打算做…(mean)" },
    { word: "prove to do sth.", meaning: "证明做…(prove)" },
    { word: "apply oneself to doing sth.", meaning: "专心做…(apply)" },
    { word: "attach importance to doing sth.", meaning: "重视做…(attach)" },
    { word: "object to doing sth.", meaning: "反对做…(object)" },
    { word: "stick to doing sth.", meaning: "坚持做…(stick)" },
    { word: "deliver a speech", meaning: "发表演讲(deliver)" },
    { word: "admire sb. for sth", meaning: "因…钦佩某人(admire)" },
    { word: "imagine doing sth.", meaning: "想象做…(imagine)" },
    { word: "appear to do sth.", meaning: "好像要做…(appear)" },
    { word: "arrange to do sth.", meaning: "安排做…(arrange)" },
    { word: "fail to do sth.", meaning: "未能做…(fail)" },
    { word: "seek to do sth.", meaning: "试图做…(seek)" },
    { word: "prepare to do sth.", meaning: "准备做…(prepare)" },
    { word: "decide to do sth.", meaning: "决定做…(decide)" },
    { word: "make a copy of", meaning: "复制;复印(copy)" },
    { word: "suffer from", meaning: "遭受;患…病(suffer)" },
    { word: "be subject to doing sth.", meaning: "受…支配;易受…影响(subject)" },
    { word: "have a dislike for", meaning: "不喜欢;讨厌(dislike,f)" },
    { word: "have a dislike of", meaning: "不喜欢;讨厌(dislike,o)" },
    { word: "shortly after", meaning: "不久之后;很快(shortly)" },
    { word: "blow up", meaning: "爆炸;发脾气(blow)" },
    { word: "blow out", meaning: "吹熄;爆裂(blow)" },
    { word: "aim at", meaning: "瞄准;旨在(aim)" },
    { word: "add up", meaning: "加起来;合计(add)" },
    { word: "add to", meaning: "增加;增添(add)" },
    { word: "introduce sb. to sb.", meaning: "把某人介绍给某人(introduce)" },
    { word: "be consumed with", meaning: "被(感情)所吞噬;因…而变得憔悴(consume)" },
    { word: "consume away", meaning: "消耗掉;憔悴;枯萎(consume)" },
    { word: "consumer goods", meaning: "消费品;生活资料(consumer)" },
    { word: "consumer rights", meaning: "消费者权益(consumer)" },
    { word: "custom of", meaning: "…的风俗;…的习惯(custom)" },
    { word: "by custom", meaning: "按照习俗;依照习惯(custom)" },
    { word: "be accustomed to", meaning: "习惯于(accustomed)" },
    { word: "export to", meaning: "出口到;输出到(export)" },
    { word: "import from", meaning: "从…进口;从…引进(import)" },
    { word: "advertise on", meaning: "在…上做广告(advertise)" },
    { word: "on schedule", meaning: "按时;按照预定时间(schedule)" },
    { word: "ahead of schedule", meaning: "提前(schedule)" },
    { word: "be punctual for", meaning: "准时(做某事)(punctual)" },
    { word: "keep one's distance from", meaning: "与…保持距离(keep)" },
    { word: "go abroad", meaning: "出国(go)" },
    { word: "dare sb. to do sth.", meaning: "激…做某事(dare)" },
    { word: "how dare sb. do sth.!", meaning: "…竟敢做…!(dare)" },
    { word: "before the deadline", meaning: "在最终期限之前(before)" },
    { word: "be curious about", meaning: "对…好奇(curious)" },
    { word: "give the speech", meaning: "发表演讲(give)" },
    { word: "smile at", meaning: "对…微笑(smile)" },
    { word: "think highly of", meaning: "高度评价;高度赞扬(think)" },
    { word: "praise sb. for doing sth.", meaning: "因做…表扬某人(praise)" },
    { word: "travel around the world", meaning: "环游世界(travel)" },
    { word: "be known for", meaning: "因…而闻名(known)" },
    { word: "be faithful to doing sth.", meaning: "对…忠诚(faithful)" },
    { word: "be in favor of doing sth.", meaning: "支持做…(favor)" },
    { word: "tell A from B", meaning: "分辨出A与B的区别(tell)" },
    { word: "come across", meaning: "偶遇(come)" },
    { word: "run into", meaning: "偶遇(run)" },
    { word: "go on", meaning: "持续(go)" },
    { word: "go out", meaning: "外出;出去(go)" },
    { word: "take steps", meaning: "采取措施(steps)" },
    { word: "take action", meaning: "采取措施(action)" },
    { word: "suffer traffic jam", meaning: "遭遇交通拥堵(suffer)" },
    { word: "place of interest", meaning: "景点;名胜古迹(place)" },
    { word: "as a result", meaning: "因此(as)" },
    { word: "go camping", meaning: "去露营(go)" },
    { word: "go fishing", meaning: "去钓鱼(go)" },
    { word: "go hiking", meaning: "去远足(go)" },
    { word: "go shopping", meaning: "去购物(go)" },
    { word: "by means of", meaning: "借助…手段;依靠…方法(means)" },
    { word: "sister-in-law", meaning: "嫂子;弟媳(sister)" },
    { word: "bring about", meaning: "引起，导致(bring)" },
    { word: "come about", meaning: "发生(come)" },
    { word: "set about", meaning: "着手，开始(set)" },
    { word: "allow doing", meaning: "准许做(allow)" },
    { word: "allow for", meaning: "考虑到(allow)" },
    { word: "allow in", meaning: "准许进入(allow)" },
    { word: "ask about", meaning: " 询问，打听(ask)" },
    { word: "ask for", meaning: "要求，请求(ask)" },
    { word: "ask off ", meaning: "请假(ask)" },
    { word: "be surprised at", meaning: "对…感到好奇(surprised)" },
    { word: "fly at", meaning: "飞向(fly)" },
    { word: "glance at", meaning: "扫视(glance)" },
    { word: "glare at", meaning: "怒视(glare)" },
    { word: "jump at", meaning: "跳向(jump)" },
    { word: "point at", meaning: "指向(point)" },
    { word: "run at", meaning: "冲向(run)" },
    { word: "shout at", meaning: "对…大声叫喊(shout)" },
    { word: "smile at sb", meaning: "冲某人笑(smile)" },
    { word: "stare at", meaning: "凝视(stare)" },
    { word: "work at", meaning: "干…活(work)" },
    { word: "at dinner", meaning: "在吃正餐(dinner)" },
    { word: "at the table", meaning: "在桌子旁(table)" },
    { word: "at the age of", meaning: "在…岁时(age)" },
    { word: "at the foot of", meaning: "在…脚下(foot)" },
    { word: "at the back of", meaning: "在…后面(back)" },
    { word: "at the end of", meaning: "在…结尾(end)" },
    { word: "blow away", meaning: "吹走(blow)" },
    { word: "break away", meaning: "摆脱(break)" },
    { word: "carry away", meaning: "拿走(carry)" },
    { word: "clear away", meaning: "消散,清除掉(clear)" },
    { word: "die away", meaning: "逐渐消失 (die)" },
    { word: "give away", meaning: "捐赠(give)" },
    { word: "pass away", meaning: "去世(pass)" },
    { word: "put away", meaning: "收拾起来(put)" },
    { word: "send away", meaning: "走开(send)" },
    { word: "take away", meaning: "拿走(take)" },
    { word: "throw away", meaning: "扔掉(throw)" },
    { word: "turn away", meaning: "把…打发走(turn)" },
    { word: "wash away", meaning: "冲走(wash)" },
    { word: "wear away", meaning: "消耗,磨掉(wear)" },
    { word: "call back", meaning: "回电话(call)" },
    { word: "give back", meaning: "归还(give)" },
    { word: "hold back", meaning: "控制住(hold)" },
    { word: "keep back", meaning: "隐瞒;忍住(keep)" },
    { word: "grown-up", meaning: "成人(grown)" },
    { word: "passer-by", meaning: "路人(passer)" },
    { word: "go-between", meaning: "中间人(between)" },
    { word: "give sb. sth.", meaning: "给…某物(give)" },
    { word: "a piece of news", meaning: "一条消息(news)" },
    { word: "a block of stone", meaning: "一块石头(stone)" },
    { word: "the former, the latter", meaning: "前者;后者(the)" },
    { word: "be of importance", meaning: "很重要(n.)" },
    { word: "be important", meaning: "很重要(adj.)" },
    { word: "finger nail", meaning: "手指甲(finger)" },
    { word: "country music", meaning: "乡村音乐(music)" },
    { word: "make an appointment with sb.", meaning: "与…有一个约会(make)" },
    { word: "a sense of belongings", meaning: "归属感(sense)" },
    { word: "tend to do sth.", meaning: "倾向于;往往会(tend)" },
    { word: "have a tendency to do sth.", meaning: "有…的倾向(have)" },
    { word: "make a decision", meaning: "做决定(make)" },
    { word: "put away", meaning: "收好;放好(put)" },
    { word: "put up", meaning: "建造;张贴(put)" },
    { word: "share sth. with sb.", meaning: "和…分享…(share)" },
    { word: "instead of", meaning: "而不是(instead)" },
    { word: "along with", meaning: "和…一起(along)" },
    { word: "go along with", meaning: "和…观点一致(along)" },
    { word: "get along with", meaning: "与…和睦相处(along)" },
    { word: "out of stock", meaning: "卖光;无存货(stock)" },
    { word: "sell out", meaning: "卖光(sell)" },
    { word: "have difficulty (in) doing sth.", meaning: "做…有困难(difficulty)" },
    { word: "inform sb. of sth.", meaning: "通知某人…(inform)" },
    { word: "remind sb. of sth.", meaning: "提醒某人…(remind)" },
    { word: "warn sb. of sth.", meaning: "警告某人…(warn)" },
    { word: "have trouble (in) doing sth.", meaning: "做…有困难(trouble)" },
    { word: "invite sb. to do sth.", meaning: "邀请某人做…(invite)" },
    { word: "be absorbed in", meaning: "专注于(absorbed)" },
    { word: "to one's relief", meaning: "令…放松的是(relief)" },
    { word: "meet the demands of", meaning: "满足…的要求(demands)" },
    { word: "meet the needs of", meaning: "满足…的需求(needs)" },
    { word: "be adequate for", meaning: "满足…的要求(adequate)" },
    { word: "ask sb. to do sth.", meaning: "请求/要求某人做…(ask)" },
    { word: "can't be too (adj.)", meaning: "再…也不为过(can't)" },
    { word: "at the same time", meaning: "同时(time)" },
    { word: "try doing", meaning: "尝试(try)" },
    { word: "gap year", meaning: "间隔年(gap)" },
    { word: "try to do", meaning: "尽力(try)" },
    { word: "work on", meaning: "致力于(work)" },
    { word: "be made of", meaning: "由…制造(看得出原材料)(make)" },
    { word: "work out", meaning: "解决(work)" },
    { word: "be made from", meaning: "由…制造(看不出原材料)(make)" },
    { word: "keep in touch with", meaning: "和…保持联系(keep)" },
    { word: "be busy doing sth.", meaning: "忙于做…(busy)" },
    { word: "in front of", meaning: "在…的前面(front)" },
    { word: "keep sb busy doing sth.", meaning: "让…忙于做某事(keep)" },
    { word: "get a pay rise", meaning: "加薪(get)" },
    { word: "stop sb. from doing sth.", meaning: "阻止…做某事(stop)" },
    { word: "prevent sb. from doing sth.", meaning: "阻止…做某事(prevent)" },
    { word: "go on a picnic", meaning: "去野餐(go)" },
    { word: "keep sb. from doing sth.", meaning: "阻止…做某事(keep)" },
    { word: "have a picnic", meaning: "去野餐(have)" },
    { word: "mean to do sth.", meaning: "打算做…(mean)" },
    { word: "go camping", meaning: "去露营(go)" },
    { word: "mean doing sth.", meaning: "意味着做…(mean)" },
    { word: "agree to do sth.", meaning: "同意做…(agree)" },
    { word: "hope to do sth.", meaning: "希望去做…(hope)" },
    { word: "agree with", meaning: "同意…的观点(agree)" },
    { word: "oblige sb. to do sth.", meaning: "迫使…做某事(oblige)" },
    { word: "force sb. to do sth.", meaning: "迫使…做某事(force)" },
    { word: "sth. be familiar to sb.", meaning: "为…所熟悉(familiar)" },
    { word: "make up", meaning: "编造;化妆;组成;弥补(make)" },
    { word: "die out", meaning: "灭绝(die)" },
    { word: "look up", meaning: "查阅(look)" },
    { word: "depend on", meaning: "依靠;取决于(depend)" },
    { word: "after all", meaning: "毕竟(after)" },
    { word: "come on", meaning: "快点;来吧(come)" },
    { word: "intend to do sth.", meaning: "意图做…(intend)" },
    { word: "see to doing sth.", meaning: "处理…(see)" },
    { word: "supply and demand", meaning: "供需" },
    { word: "refer to doing sth.", meaning: "提到/参考…(refer)" },
    { word: "it is likely that", meaning: "可能做…(likely)" },
    { word: "take up", meaning: "占据;拿起;开始从事(take)" },
    { word: "be likely to do sth.", meaning: "可能做…(likely)" },
    { word: "set aside", meaning: "留出(set)" },
    { word: "prefer A to B", meaning: "比起B更喜欢A(prefer)" },
    { word: "turn down", meaning: "拒绝;调低(turn)" },
    { word: "prefer doing A to doing B", meaning: "比起做B更喜欢做A(prefer)" },
    { word: "prefer to do A rather than do B", meaning: "更喜欢A而不是B(prefer)" },
    { word: "make friends with sb.", meaning: "与…交朋友(make)" },
    { word: "put off", meaning: "推迟(put)" },
    { word: "cut off", meaning: "切断(cut)" },
    { word: "turn over", meaning: "翻转(turn)" },
    { word: "from time to time", meaning: "时不时地(time)" },
    { word: "break down", meaning: "出故障(break)" },
    { word: "break up", meaning: "分手;破裂(break)" },
    { word: "get through", meaning: "通过(get)" },
    { word: "go on", meaning: "继续(go)" },
    { word: "keep on", meaning: "继续(keep)" },
    { word: "carry on", meaning: "继续(carry)" },
    { word: "insist on doing sth.", meaning: "坚持做…(insist)" },
    { word: "catch up with", meaning: "赶上(catch)" }
];
