export const wordList = [
    { word: "divide… into…", meaning: "把…分成…(divide)" },
    { word: "by the time", meaning: "到…为止(time)" },
    { word: "make sure", meaning: "确保(sure)" },
    { word: "have a hard time doing sth.", meaning: "做…有困难(time)" },
    { word: "prepare for", meaning: "为…做准备(prepare)" },
    { word: "make great contributions to sth.", meaning: "对…做出巨大贡献(contribution)" },
    { word: "had better (not) do sth.", meaning: "最好(不)做…(better)" },
    { word: "avoid doing sth.", meaning: "避免做…(avoid)" },
    { word: "be fond of doing sth.", meaning: "喜欢做…(fond)" },
    { word: "in person", meaning: "亲自(person)" },
    { word: "stay awake", meaning: "保持清醒(awake)" },
    { word: "make room for", meaning: "为…腾出空间(room)" },
    { word: "give sb. some advice on", meaning: "给某人关于…的一些建议(advice)" },
    { word: "go to bed", meaning: "上床睡觉(bed)" },
    { word: "remember to do sth.", meaning: "记得要做…(remember)" },
    { word: "remember doing sth.", meaning: "记得做过…(remember)" },
    { word: "would you like to do sth.", meaning: "你愿意做…吗(would)" },
    { word: "be so interested in", meaning: "对…如此感兴趣(interested)" },
    { word: "improve living standards", meaning: "提升生活水平(standard)" },
    { word: "take pride in", meaning: "以…为傲(pride)" },
    { word: "be proud of", meaning: "以…为傲(proud)" },
    { word: "enjoy doing sth.", meaning: "喜欢做…(enjoy)" },
    { word: "make comments on", meaning: "就…做评价(comment)" },
    { word: "self-introduction", meaning: "自我介绍(introduction)" },
    { word: "take place", meaning: "发生(place)" },
    { word: "take the place of", meaning: "取代(place)" },
    { word: "get rid of", meaning: "去除，摆脱(rid)" },
    { word: "divide into", meaning: "分为(divide)" },
    { word: "put… into action", meaning: "把…付诸实践(action)" },
    { word: "put… into practice", meaning: "把…付诸实践(practice)" },
    { word: "attract one's attention", meaning: "吸引某人的注意力(attract)" },
    { word: "draw one's attention", meaning: "吸引某人的注意力(draw)" },
    { word: "catch one's attention", meaning: "吸引某人的注意力(catch)" },
    { word: "pay attention to doing sth.", meaning: "注意做…(attention)" },
    { word: "tend to do sth.", meaning: "往往会做…(tend)" },
    { word: "achieve one's dream", meaning: "实现某人的梦想(achieve)" },
    { word: "make one's dream come true", meaning: "实现某人的梦想(come)" },
    { word: "out of", meaning: "出自，缺少，脱离(out)" },
    { word: "in addition to doing sth.", meaning: "除了做…之外还有(addition)" },
    { word: "at all", meaning: "根本，究竟(all)" },
    { word: "a lack of", meaning: "缺乏(lack->n.)" },
    { word: "lacking in", meaning: "缺乏(lack->adj.)" },
    { word: "be caught in the rain", meaning: "淋雨(catch)" },
    { word: "much to one's surprise", meaning: "令某人非常惊讶的是(much)" },
    { word: "different kinds of", meaning: "不同种类的(kind)" },
    { word: "sing high praise for", meaning: "高度赞扬(praise)" },
    { word: "play an important role in", meaning: "在…中扮演重要角色(role)" },
    { word: "play an important part in", meaning: "在…方面起重要作用(part)" },
    { word: "sb. be devoted to doing sth.", meaning: "某人投身于做…(devoted)" },
    { word: "devotion to doing sth.", meaning: "对做…的奉献(devotion)" },
    { word: "manage to do sth.", meaning: "设法做…(manage)" },
    { word: "a variety of", meaning: "各种各样的(variety)" },
    { word: "be likely to do sth.", meaning: "很可能会做…(likely to)" },
    { word: "it is likely that", meaning: "很可能…(likely that)" },
    { word: "whether… or…", meaning: "(无论)是…还是…(whether)" },
    { word: "whether or not", meaning: "(无论)是否(whether)" },
    { word: "whether or no", meaning: "无论如何(whether)" },
    { word: "blow away", meaning: "吹走，深深打动(blow)" },
    { word: "bring down", meaning: "降低，打倒(bring)" },
    { word: "put into action", meaning: "付诸行动(action)" },
    { word: "put into practice", meaning: "付诸行动(practice)" },
    { word: "keep in touch with", meaning: "与…保持联系(touch)" },
    { word: "one day", meaning: "总有一天(day)" },
    { word: "by all means", meaning: "当然，无论如何，用一切手段(all)" },
    { word: "by any means", meaning: "通过任何方式，无论如何(any)" },
    { word: "by no means", meaning: "决不，绝不(no)" },
    { word: "by means of", meaning: "通过/依靠…(方法)(means)" },
    { word: "be to blame for sth.", meaning: "应受谴责，应负责任(blame)" },
    { word: "blame sb. for sth.", meaning: "因…责怪某人(blame)" },
    { word: "blame on", meaning: "归咎于…(blame)" },
    { word: "be different from", meaning: "与…不同(different)" },
    { word: "the same as", meaning: "与…相同(same)" },
    { word: "be similar to sth.", meaning: "与…相似(similar)" },
    { word: "try one's best", meaning: "尽某人最大努力(try)" },
    { word: "make the best of", meaning: "尽力而为，充分利用(make)" },
    { word: "all the best", meaning: "万事如意，一切顺利(all)" },
    { word: "on condition that", meaning: "条件是(condition)" },
    { word: "be in good condition", meaning: "状态良好(condition)" },
    { word: "be in bad condition", meaning: "状态不佳(condition)" },
    { word: "enjoy yourself", meaning: "祝你玩得开心，请自便(enjoy)" },
    { word: "enjoy oneself", meaning: "玩得开心(enjoy)" },
    { word: "make oneself at home", meaning: "别客气(home)" },
    { word: "help yourself to doing sth.", meaning: "请自便…(help)" },
    { word: "by oneself", meaning: "独自，靠某人自己(by)" },
    { word: "put off", meaning: "推迟(put)" },
    { word: "complain about", meaning: "抱怨(complain)" },
    { word: "had fun (in) doing sth.", meaning: "做…很开心(fun)" },
    { word: "set a good example for", meaning: "为…树立好榜样(example)" },
    { word: "set good examples for", meaning: "为…树立好榜样(examples)" },
    { word: "be far away from", meaning: "远离，距…远(far)" },
    { word: "on time", meaning: "准时(time)" },
    { word: "in time", meaning: "及时(time)" },
    { word: "spend time doing sth.", meaning: "花时间做…(spend)" },
    { word: "spend time on", meaning: "在…上花时间(spend)" },
    { word: "come to oneself", meaning: "苏醒(come)" },
    { word: "get lost", meaning: "迷路(lost)" },
    { word: "be strict with sb.", meaning: "对…要求严格(strict)" },
    { word: "so far", meaning: "到目前为止，到这种程度(far)" },
    { word: "help sb. with", meaning: "帮助某人解决某种问题(help)" },
    { word: "help sb. do sth.", meaning: "帮助某人做…(help)" },
    { word: "with one's help", meaning: "在某人的帮助下(help)" },
    { word: "with the help of sb.", meaning: "在…的帮助下(the help)" },
    { word: "mind doing sth.", meaning: "介意做…(mind)" },
    { word: "result in", meaning: "导致…(result)" },
    { word: "result from", meaning: "由…导致(result)" },
    { word: "try to do sth.", meaning: "尽力做…(try)" },
    { word: "try doing sth.", meaning: "尝试做…(try)" },
    { word: "push in", meaning: "插队(push)" },
    { word: "cut in", meaning: "插队\\嘴\\入(cut)" },
    { word: "stop to do sth.", meaning: "停下…去做…(stop)" },
    { word: "stop doing sth.", meaning: "停下(正在做的…)(stop)" },
    { word: "in order that", meaning: "为了(+从句)(order)" },
    { word: "in order to do sth.", meaning: "为了(+do)(order)" },
    { word: "search for", meaning: "寻找(search)" },
    { word: "look for", meaning: "寻找(look)" },
    { word: "waste time doing sth.", meaning: "浪费时间做…(waste)" },
    { word: "waste time on sth.", meaning: "在…浪费时间(waste)" },
    { word: "lose touch with sb.", meaning: "与…失联(touch)" },
    { word: "put on", meaning: "穿上(put)" },
    { word: "apply for", meaning: "申请(apply)" },
    { word: "be seriously hurt", meaning: "受重伤(hurt)" },
    { word: "at once", meaning: "立刻(at)" },
    { word: "right now", meaning: "立刻(now)" },
    { word: "right away", meaning: "立刻(away)" },
    { word: "fall in love with sb.", meaning: "爱上…(fall)" },
    { word: "fall in love", meaning: "坠入爱河(fall)" },
    { word: "be in love with sb.", meaning: "爱上…(be)" },
    { word: "put emphasis on", meaning: "强调…(put)" },
    { word: "attach important to sth.", meaning: "重视…(important)" },
    { word: "turn up", meaning: "出现，调高(音量…)(turn)" },
    { word: "turn down", meaning: "拒绝，调低(音量…)(turn)" },
    { word: "take care of", meaning: "照顾，支付(尤指替他人)(care)" },
    { word: "a stark contrast to sth.", meaning: "与…形成鲜明对比(contrast)" },
    { word: "make a good impression on", meaning: "给…留下好印象(impression)" },
    { word: "not… but…", meaning: "不是…而是(not)" },
    { word: "put away", meaning: "收起，储存，将…送进(监狱…)(put)" },
    { word: "be eager to do sth.", meaning: "渴望做…(eager)" },
    { word: "around the world", meaning: "全世界(around)" },
    { word: "all over the world", meaning: "全世界(all)" },
    { word: "decide to do sth.", meaning: "决定做…(decide)" },
    { word: "in front of", meaning: "在(外部的)…前面(front)" },
    { word: "in the front of", meaning: "在…(内部的)前面(front)" },
    { word: "it takes sb. 时间/金钱 to do sth.", meaning: "某人花费多长时间/多少钱做…(take)" },
    { word: "in other words", meaning: "换言之(words)" },
    { word: "have the potential to do sth.", meaning: "有潜力做…(have)" },
    { word: "live a(n) [adj.] life", meaning: "过着…的生活(life)" },
    { word: "be inspired by", meaning: "被…启发/鼓舞(be)" },
    { word: "have nothing to do with", meaning: "与…无关(nothing)" },
    { word: "be severely punished", meaning: "受到严厉惩罚(punished)" },
    { word: "make full use of", meaning: "充分利用(use)" },
    { word: "have a good command of", meaning: "精通…(command)" },
    { word: "be ready to do sth.", meaning: "准备/愿意/乐意做…(ready)" },
    { word: "arouse the awareness of", meaning: "唤起对…的意识(arouse)" },
    { word: "have a picnic", meaning: "去野餐(have)" },
    { word: "offer sb. sth.", meaning: "提供某人…(offer)" },
    { word: "offer sth. to sb.", meaning: "提供…给某人(offer)" },
    { word: "help sb. (to) do sth.", meaning: "帮助某人做…(help)" },
    { word: "intend sb.to do sth.", meaning: "打算要某人做…(intend)" },
    { word: "invite sb.to do sth.", meaning: "邀请某人做…(invite)" },
    { word: "provide sb. with sth.", meaning: "提供某人…(provide)" },
    { word: "provide sth. for sb.", meaning: "提供…给某人(provide)" },
    { word: "hear of", meaning: "听说(hear)" },
    { word: "start to do sth.", meaning: "开始做…(start)" },
    { word: "such as", meaning: "例如(such)" },
    { word: "from time to time", meaning: "时不时(time)" },
    { word: "be of great importance", meaning: "非常重要(importance)" },
    { word: "to begin with", meaning: "首先(begin)" },
    { word: "take up one's spare time", meaning: "占用某人的空闲时间(take)" },
    { word: "in addition", meaning: "此外(addition)" },
    { word: "make a wise choice of", meaning: "做一个明智的…的选择(choice)" },
    { word: "set up", meaning: "建立，设置，安排(set)" },
    { word: "encourage sb. to do sth.", meaning: "鼓励某人做…(encourage)" },
    { word: "focus on", meaning: "专注/集中/聚焦/侧重于(focus)" },
    { word: "have… in common", meaning: "在…有共同点(common)" },
    { word: "force sb. to do sth.", meaning: "强迫某人做…(force)" },
    { word: "up and down", meaning: "上上下下(and)" },
    { word: "jump up and down", meaning: "跳上跳下(and)" },
    { word: "my suggestions are as follows", meaning: "我的建议如下(suggestion)" },
    { word: "aim to do sth.", meaning: "打算做…(aim)" },
    { word: "ask to do sth.", meaning: "要求做…(ask)" },
    { word: "finish doing sth.", meaning: "完成做…(finish)" },
    { word: "give up doing sth.", meaning: "放弃做…(give)" },
    { word: "forbid doing sth.", meaning: "禁止做…(forbid)" },
    { word: "miss doing sth.", meaning: "错过做…(miss)" },
    { word: "pardon doing sth.", meaning: "原谅做…(pardon)" },
    { word: "refuse to do sth.", meaning: "拒绝做…(refuse)" },
    { word: "offer to do sth.", meaning: "主动提出做…(offer)" },
    { word: "expect to do sth.", meaning: "期望做…(expect)" },
    { word: "wish to do sth.", meaning: "希望做…(wish)" },
    { word: "hope to do sth.", meaning: "希望做…(hope)" },
    { word: "permit doing sth.", meaning: "允许做…(permit)" },
    { word: "practise doing sth.", meaning: "练习做…(practise)" },
    { word: "prevent doing sth.", meaning: "阻止做…(prevent)" },
    { word: "want to do sth.", meaning: "想要做…(want)" },
    { word: "consider doing sth.", meaning: "考虑做…(consider)" },
    { word: "delay doing sth.", meaning: "推迟做…(delay)" },
    { word: "there is no denying", meaning: "不可否认(deny)" },
    { word: "deny doing sth.", meaning: "否认做…(deny)" },
    { word: "keep doing sth.", meaning: "继续做…(keep)" },
    { word: "long to do sth.", meaning: "渴望做…(long)" },
    { word: "fear to do sth.", meaning: "害怕做…(fear)" },
    { word: "beg to do sth.", meaning: "请求做…(beg)" },
    { word: "struggle to do sth.", meaning: "努力做…(struggle)" },
    { word: "dare to do sth.", meaning: "敢于做…(dare)" },
    { word: "expect to do sth.", meaning: "期望做…(expect)" },
    { word: "force sb.to do sth.", meaning: "强迫某人做…(force)" },
    { word: "expect sb.to do sth.", meaning: "期望某人做…(expect)" },
    { word: "want sb. to do sth", meaning: "想要某人做…(want)" },
    { word: "warn sb. to do sth.", meaning: "警告某人做…(warn)" },
    { word: "would rather do sth.", meaning: "宁愿做…(would)" },
    { word: "may as well do sth.", meaning: "不妨做…(may)" },
    { word: "might as well do sth.", meaning: "不妨做…(might)" },
    { word: "can't help but do sth.", meaning: "忍不住做…(help)" },
    { word: "do nothing but do", meaning: "除了做…之外…也不做(but)" },
    { word: "have nothing to do but do", meaning: "除了做…之外别无选择(but)" },
    { word: "take to doing sth.", meaning: "逐渐习惯做…(take)" },
    { word: "sth. need doing", meaning: "…需要被做(need)" },
    { word: "sth. want doing", meaning: "…需要被做(want)" },
    { word: "sth. require doing", meaning: "…需要被做(require)" },
    { word: "sth. be worth doing", meaning: "…值得被做(worth)" },
    { word: "demand to do sth.", meaning: "要求做…(demand)" },
    { word: "happen to do sth.", meaning: "碰巧做…(happen)" },
    { word: "hesitate to do sth.", meaning: "犹豫做…(hesitate)" },
    { word: "plan to do sth.", meaning: "计划做…(plan)" },
    { word: "wait to do sth.", meaning: "等待做…(wait)" },
    { word: "be worthy of doing", meaning: "值得做…(worthy)" },
    { word: "admit doing sth.", meaning: "承认做…(admit)" },
    { word: "advise doing sth.", meaning: "建议做…(advise)" },
    { word: "allow doing sth.", meaning: "允许做…(allow)" },
    { word: "appreciate doing sth.", meaning: "感激做…(appreciate)" },
    { word: "can't help doing sth.", meaning: "忍不住做…(help)" },
    { word: "mention doing sth.", meaning: "提及做…(mention)" },
    { word: "mind doing sth.", meaning: "介意做…(mind)" },
    { word: "discuss doing sth.", meaning: "谈论做…(discuss)" },
    { word: "dislike doing sth.", meaning: "讨厌做…(dislike)" },
    { word: "be accustomed to doing sth.", meaning: "习惯做…(accustom)" },
    { word: "be opposed to doing sth.", meaning: "反对做…(oppose)" },
    { word: "confess to doing sth.", meaning: "承认做了…(confess)" },
    { word: "look forward to doing sth.", meaning: "期待做…(look)" },
    { word: "enjoy doing sth.", meaning: "喜欢做…(enjoy)" },
    { word: "escape doing sth.", meaning: "逃脱做…(escape)" },
    { word: "excuse doing sth.", meaning: "借口做…(excuse)" },
    { word: "learn to do sth.", meaning: "学会做…(learn)" },
    { word: "care to do sth.", meaning: "想要做…(care)" },
    { word: "afford to do sth.", meaning: "负担得起做…(afford)" },
    { word: "explain doing sth.", meaning: "解释做…(explain)" },
    { word: "fancy doing sth.", meaning: "设想做…(fancy)" },
    { word: "prohibit doing sth.", meaning: "禁止做…(prohibit)" },
    { word: "put off doing sth.", meaning: "推迟做…(put)" },
    { word: "agree to do sth.", meaning: "同意做…(agree)" },
    { word: "choose to do sth.", meaning: "选择/决定做…(choose)" },
    { word: "pretend to do sth.", meaning: "假装做…(pretend)" },
    { word: "promise to do sth.", meaning: "答应做…(promise)" },
    { word: "recall doing sth.", meaning: "回忆起做了…(recall)" },
    { word: "report doing sth.", meaning: "报告做了…(report)" },
    { word: "be reported to do sth.", meaning: "据报告做了…(report)" },
    { word: "resist doing sth.", meaning: "拒绝做…(resist)" },
    { word: "risk doing sth.", meaning: "冒险做…(risk)" },
    { word: "suggest doing sth.", meaning: "建议做…(suggest)" },
    { word: "understand doing sth.", meaning: "理解做…(understand)" },
    { word: "determine to do sth.", meaning: "决定做…(determine)" },
    { word: "mean to do sth.", meaning: "打算做…(mean)" },
    { word: "prove to do sth.", meaning: "证明做…(prove)" },
    { word: "apply oneself to doing sth.", meaning: "专心做…(apply)" },
    { word: "attach importance to doing sth.", meaning: "重视做…(attach)" },
    { word: "object to doing sth.", meaning: "反对做…(object)" },
    { word: "stick to doing sth.", meaning: "坚持做…(stick)" },
    { word: "deliver a speech", meaning: "发表演讲(deliver)" },
    { word: "admire sb. for sth", meaning: "因…钦佩某人(admire)" },
    { word: "imagine doing sth.", meaning: "想象做…(imagine)" },
    { word: "appear to do sth.", meaning: "好像要做…(appear)" },
    { word: "arrange to do sth.", meaning: "安排做…(arrange)" },
    { word: "fail to do sth.", meaning: "未能做…(fail)" },
    { word: "seek to do sth.", meaning: "试图做…(seek)" },
    { word: "prepare to do sth.", meaning: "准备做…(prepare)" },
    { word: "decide to do sth.", meaning: "决定做…(decide)" },
    { word: "make a copy of", meaning: "复制;复印(copy)" },
    { word: "suffer from", meaning: "遭受;患…病(suffer)" },
    { word: "be subject to doing sth.", meaning: "受…支配;易受…影响(subject)" },
    { word: "have a dislike for", meaning: "不喜欢;讨厌(dislike,f)" },
    { word: "have a dislike of", meaning: "不喜欢;讨厌(dislike,o)" },
    { word: "shortly after", meaning: "不久之后;很快(shortly)" },
    { word: "blow up", meaning: "爆炸;发脾气(blow)" },
    { word: "blow out", meaning: "吹熄;爆裂(blow)" },
    { word: "aim at", meaning: "瞄准;旨在(aim)" },
    { word: "add up", meaning: "加起来;合计(add)" },
    { word: "add to", meaning: "增加;增添(add)" },
    { word: "introduce sb. to sb.", meaning: "把某人介绍给某人(introduce)" },
    { word: "be consumed with", meaning: "被(感情)所吞噬;因…而变得憔悴(consume)" },
    { word: "consume away", meaning: "消耗掉;憔悴;枯萎(consume)" },
    { word: "consumer goods", meaning: "消费品;生活资料(consumer)" },
    { word: "consumer rights", meaning: "消费者权益(consumer)" },
    { word: "custom of", meaning: "…的风俗;…的习惯(custom)" },
    { word: "by custom", meaning: "按照习俗;依照习惯(custom)" },
    { word: "be accustomed to doing sth.", meaning: "习惯于(accustomed)" },
    { word: "export to doing sth.", meaning: "出口到;输出到(export)" },
    { word: "import from", meaning: "从…进口;从…引进(import)" },
    { word: "advertise on", meaning: "在…上做广告(advertise)" },
    { word: "on schedule", meaning: "按时;按照预定时间(schedule)" },
    { word: "ahead of schedule", meaning: "提前(schedule)" },
    { word: "be punctual for", meaning: "准时(做某事)(punctual)" },
    { word: "keep one's distance from", meaning: "与…保持距离(keep)" },
    { word: "go abroad", meaning: "出国(go)" },
    { word: "dare sb. to do sth.", meaning: "激…做某事(dare)" },
    { word: "how dare sb. do sth.!", meaning: "…竟敢做…!(dare)" },
    { word: "before the deadline", meaning: "在最终期限之前(before)" },
    { word: "be curious about", meaning: "对…好奇(curious)" },
    { word: "give the speech", meaning: "发表演讲(give)" },
    { word: "smile at", meaning: "对…微笑(smile)" },
    { word: "think highly of", meaning: "高度评价;高度赞扬(think)" },
    { word: "praise sb. for doing sth.", meaning: "因做…表扬某人(praise)" },
    { word: "travel around the world", meaning: "环游世界(travel)" },
    { word: "be known for", meaning: "因…而闻名(known)" },
    { word: "be faithful to doing sth.", meaning: "对…忠诚(faithful)" },
    { word: "be in favor of doing sth.", meaning: "支持做…(favor)" },
    { word: "tell A from B", meaning: "分辨出A与B的区别(tell)" },
    { word: "come across", meaning: "偶遇(come)" },
    { word: "run into", meaning: "偶遇(run)" },
    { word: "go on", meaning: "持续(go)" },
    { word: "go out", meaning: "外出;出去(go)" },
    { word: "take steps", meaning: "采取措施(steps)" },
    { word: "take action", meaning: "采取措施(action)" },
    { word: "suffer traffic jam", meaning: "遭遇交通拥堵(suffer)" },
    { word: "place of interest", meaning: "景点;名胜古迹(place)" },
    { word: "as a result", meaning: "因此(as)" },
    { word: "go camping", meaning: "去露营(go)" },
    { word: "go fishing", meaning: "去钓鱼(go)" },
    { word: "go hiking", meaning: "去远足(go)" },
    { word: "go shopping", meaning: "去购物(go)" },
    { word: "by means of", meaning: "借助…手段;依靠…方法(means)" },
    { word: "sister-in-law", meaning: "嫂子;弟媳(sister)" },
    { word: "bring about", meaning: "引起，导致(bring)" },
    { word: "come about", meaning: "发生(come)" },
    { word: "set about", meaning: "着手，开始(set)" },
    { word: "allow doing", meaning: "准许做(allow)" },
    { word: "allow for", meaning: "考虑到(allow)" },
    { word: "allow in", meaning: "准许进入(allow)" },
    { word: "ask about", meaning: " 询问，打听(ask)" },
    { word: "ask for", meaning: "要求，请求(ask)" },
    { word: "ask off ", meaning: "请假(ask)" },
    { word: "be surprised at", meaning: "对…感到好奇(surprised)" },
    { word: "fly at", meaning: "飞向(fly)" },
    { word: "glance at", meaning: "扫视(glance)" },
    { word: "glare at", meaning: "怒视(glare)" },
    { word: "jump at", meaning: "跳向(jump)" },
    { word: "point at", meaning: "指向(point)" },
    { word: "run at", meaning: "冲向(run)" },
    { word: "shout at", meaning: "对…大声叫喊(shout)" },
    { word: "smile at sb", meaning: "冲某人笑(smile)" },
    { word: "stare at", meaning: "凝视(stare)" },
    { word: "work at", meaning: "干…活(work)" },
    { word: "at dinner", meaning: "在吃正餐(dinner)" },
    { word: "at the table", meaning: "在桌子旁(table)" },
    { word: "at the age of", meaning: "在…岁时(age)" },
    { word: "at the foot of", meaning: "在…脚下(foot)" },
    { word: "at the back of", meaning: "在…后面(back)" },
    { word: "at the end of", meaning: "在…结尾(end)" },
    { word: "blow away", meaning: "吹走(blow)" },
    { word: "break away", meaning: "摆脱(break)" },
    { word: "carry away", meaning: "拿走(carry)" },
    { word: "clear away", meaning: "消散,清除掉(clear)" },
    { word: "die away", meaning: "逐渐消失 (die)" },
    { word: "give away", meaning: "捐赠(give)" },
    { word: "pass away", meaning: "去世(pass)" },
    { word: "put away", meaning: "收拾起来(put)" },
    { word: "send away", meaning: "走开(send)" },
    { word: "take away", meaning: "拿走(take)" },
    { word: "throw away", meaning: "扔掉(throw)" },
    { word: "turn away", meaning: "把…打发走(turn)" },
    { word: "wash away", meaning: "冲走(wash)" },
    { word: "wear away", meaning: "消耗,磨掉(wear)" },
    { word: "call back", meaning: "回电话(call)" },
    { word: "give back", meaning: "归还(give)" },
    { word: "hold back", meaning: "控制住(hold)" },
    { word: "keep back", meaning: "隐瞒;忍住(keep)" },
    { word: "grown-up", meaning: "成人(grown)" },
    { word: "passer-by", meaning: "路人(passer)" },
    { word: "go-between", meaning: "中间人(between)" },
    { word: "give sb. sth.", meaning: "给…某物(give)" },
    { word: "a piece of news", meaning: "一条消息(news)" },
    { word: "a block of stone", meaning: "一块石头(stone)" },
    { word: "the former, the latter", meaning: "前者;后者(the)" },
    { word: "be of importance", meaning: "很重要(n.)" },
    { word: "be important", meaning: "很重要(adj.)" },
    { word: "finger nail", meaning: "手指甲(finger)" },
    { word: "country music", meaning: "乡村音乐(music)" },
    { word: "make an appointment with sb.", meaning: "与…有一个约会(make)" },
    { word: "a sense of belongings", meaning: "归属感(sense)" },
    { word: "tend to do sth.", meaning: "倾向于;往往会(tend)" },
    { word: "have a tendency to do sth.", meaning: "有…的倾向(have)" },
    { word: "make a decision", meaning: "做决定(make)" },
    { word: "put away", meaning: "收好;放好(put)" },
    { word: "put up", meaning: "建造;张贴(put)" },
    { word: "share sth. with sb.", meaning: "和…分享…(share)" },
    { word: "instead of", meaning: "而不是(instead)" },
    { word: "along with", meaning: "和…一起(along)" },
    { word: "go along with", meaning: "和…观点一致(along)" },
    { word: "get along with", meaning: "与…和睦相处(along)" },
    { word: "out of stock", meaning: "卖光;无存货(stock)" },
    { word: "sell out", meaning: "卖光(sell)" },
    { word: "have difficulty (in) doing sth.", meaning: "做…有困难(difficulty)" },
    { word: "inform sb. of sth.", meaning: "通知某人…(inform)" },
    { word: "remind sb. of sth.", meaning: "提醒某人…(remind)" },
    { word: "warn sb. of sth.", meaning: "警告某人…(warn)" },
    { word: "have trouble (in) doing sth.", meaning: "做…有困难(trouble)" },
    { word: "invite sb. to do sth.", meaning: "邀请某人做…(invite)" },
    { word: "be absorbed in", meaning: "专注于(absorbed)" },
    { word: "to one's relief", meaning: "令…放松的是(relief)" },
    { word: "meet the demands of", meaning: "满足…的要求(demands)" },
    { word: "meet the needs of", meaning: "满足…的需求(needs)" },
    { word: "be adequate for", meaning: "满足…的要求(adequate)" },
    { word: "ask sb. to do sth.", meaning: "请求/要求某人做…(ask)" },
    { word: "can't be too (adj.)", meaning: "再…也不为过(can't)" },
    { word: "at the same time", meaning: "同时(time)" },
    { word: "try doing", meaning: "尝试(try)" },
    { word: "gap year", meaning: "间隔年(gap)" },
    { word: "try to do", meaning: "尽力(try)" },
    { word: "work on", meaning: "致力于(work)" },
    { word: "be made of", meaning: "由…制造(看得出原材料)(make)" },
    { word: "work out", meaning: "解决(work)" },
    { word: "be made from", meaning: "由…制造(看不出原材料)(make)" },
    { word: "keep in touch with", meaning: "和…保持联系(keep)" },
    { word: "be busy doing sth.", meaning: "忙于做…(busy)" },
    { word: "in front of", meaning: "在…的前面(front)" },
    { word: "keep sb busy doing sth.", meaning: "让…忙于做某事(keep)" },
    { word: "get a pay rise", meaning: "加薪(get)" },
    { word: "stop sb. from doing sth.", meaning: "阻止…做某事(stop)" },
    { word: "prevent sb. from doing sth.", meaning: "阻止…做某事(prevent)" },
    { word: "go on a picnic", meaning: "去野餐(go)" },
    { word: "keep sb. from doing sth.", meaning: "阻止…做某事(keep)" },
    { word: "have a picnic", meaning: "去野餐(have)" },
    { word: "mean to do sth.", meaning: "打算做…(mean)" },
    { word: "go camping", meaning: "去露营(go)" },
    { word: "mean doing sth.", meaning: "意味着做…(mean)" },
    { word: "agree to do sth.", meaning: "同意做…(agree)" },
    { word: "hope to do sth.", meaning: "希望去做…(hope)" },
    { word: "agree with", meaning: "同意…的观点(agree)" },
    { word: "oblige sb. to do sth.", meaning: "迫使…做某事(oblige)" },
    { word: "force sb. to do sth.", meaning: "迫使…做某事(force)" },
    { word: "sth. be familiar to sb.", meaning: "为…所熟悉(familiar)" },
    { word: "make up", meaning: "编造;化妆;组成;弥补(make)" },
    { word: "die out", meaning: "灭绝(die)" },
    { word: "look up", meaning: "查阅(look)" },
    { word: "depend on", meaning: "依靠;取决于(depend)" },
    { word: "after all", meaning: "毕竟(after)" },
    { word: "come on", meaning: "快点;来吧(come)" },
    { word: "intend to do sth.", meaning: "意图做…(intend)" },
    { word: "see to doing sth.", meaning: "处理…(see)" },
    { word: "supply and demand", meaning: "供需" },
    { word: "refer to doing sth.", meaning: "提到/参考…(refer)" },
    { word: "it is likely that", meaning: "可能做…(likely)" },
    { word: "take up", meaning: "占据;拿起;开始从事(take)" },
    { word: "be likely to do sth.", meaning: "可能做…(likely)" },
    { word: "set aside", meaning: "留出(set)" },
    { word: "prefer A to B", meaning: "比起B更喜欢A(prefer)" },
    { word: "turn down", meaning: "拒绝;调低(turn)" },
    { word: "prefer doing A to doing B", meaning: "比起做B更喜欢做A(prefer)" },
    { word: "prefer to do A rather than do B", meaning: "宁愿做A,也不愿做B(prefer)" },
    { word: "make friends with sb.", meaning: "与…交朋友(make)" },
    { word: "put off", meaning: "推迟(put)" },
    { word: "cut off", meaning: "切断(cut)" },
    { word: "turn over", meaning: "翻转(turn)" },
    { word: "from time to time", meaning: "时不时地(time)" },
    { word: "break down", meaning: "出故障(break)" },
    { word: "break up", meaning: "分手;破裂(break)" },
    { word: "get through", meaning: "通过(get)" },
    { word: "go on", meaning: "继续(go)" },
    { word: "keep on", meaning: "继续(keep)" },
    { word: "carry on", meaning: "继续(carry)" },
    { word: "insist on doing sth.", meaning: "坚持做…(insist)" },
    { word: "catch up with", meaning: "赶上(catch)" },
    { word: "look back", meaning: "回顾(back)" },
    { word: "take back", meaning: "拿回；退回(back)" },
    { word: "be angry with sb", meaning: "生某人的气(angry)" },
    { word: "be at home", meaning: "在家(home)" },
    { word: "be at work", meaning: "在工作(work)" },
    { word: "be back", meaning: "回来(back)" },
    { word: "be in", meaning: "在家；在里面(in)" },
    { word: "be out", meaning: "外出；不在(out)" },
    { word: "be born", meaning: "出生(born)" },
    { word: "be afraid of", meaning: "害怕(afraid)" },
    { word: "be busy doing", meaning: "忙于做(busy)" },
    { word: "be covered with", meaning: "覆盖着(covered)" },
    { word: "be famous for", meaning: "因…而出名(famous)" },
    { word: "be from", meaning: "来自(from)" },
    { word: "be glad to do sth.", meaning: "高兴做某事(glad)" },
    { word: "be good at", meaning: "擅长(good)" },
    { word: "be careful of", meaning: "小心；留意(careful)" },
    { word: "be in trouble", meaning: "处于困境(trouble)" },
    { word: "be interested in", meaning: "对…感兴趣(interested)" },
    { word: "be angry about", meaning: "因…生气(angry)" },
    { word: "be anxious about", meaning: "为…焦虑(anxious)" },
    { word: "be careful about", meaning: "对…谨慎(careful)" },
    { word: "be certain about", meaning: "对…确定(certain)" },
    { word: "be crazy about", meaning: "对…痴迷(crazy)" },
    { word: "be curious about", meaning: "对…好奇(curious)" },
    { word: "be disappointed about", meaning: "对…失望(disappointed)" },
    { word: "be excited about", meaning: "对…感到兴奋(excited)" },
    { word: "be angry at", meaning: "因…生气(angry)" },
    { word: "be bad at", meaning: "不擅长(bad)" },
    { word: "be disappointed at", meaning: "对…失望(disappointed)" },
    { word: "be expert at", meaning: "擅长；精通(expert)" },
    { word: "be good at", meaning: "擅长(good)" },
    { word: "be anxious for", meaning: "渴望；为…焦虑(anxious)" },
    { word: "be bad for", meaning: "对…有害(bad)" },
    { word: "be bound for", meaning: "前往(bound)" },
    { word: "be celebrated for", meaning: "因…而著名(celebrated)" },
    { word: "be late for", meaning: "迟到(late)" },
    { word: "be made from", meaning: "由…制成（看不出原材料）(made)" },
    { word: "be made of", meaning: "由…制成（看得出原材料）(made)" },
    { word: "be ready for", meaning: "为…做好准备(ready)" },
    { word: "be satisfied with", meaning: "对…感到满意(satisfied)" },
    { word: "be surprised at", meaning: "对…感到惊讶(surprised)" },
    { word: "be glad about", meaning: "对…感到高兴(glad)" },
    { word: "be happy about", meaning: "对…感到开心(happy)" },
    { word: "be hopeful about", meaning: "对…抱有希望(hopeful)" },
    { word: "be sad about", meaning: "对…感到难过(sad)" },
    { word: "be serious about", meaning: "对…认真(serious)" },
    { word: "be sure about", meaning: "对…确定(sure)" },
    { word: "be worried about", meaning: "对…担心(worried)" },
    { word: "be mad at", meaning: "对…生气(mad)" },
    { word: "be quick at", meaning: "在…方面敏捷(quick)" },
    { word: "be skillful at", meaning: "在…方面熟练(skillful)" },
    { word: "be slow at", meaning: "在…方面迟缓(slow)" },
    { word: "be eager for", meaning: "渴望(eager)" },
    { word: "be famous for", meaning: "因…而著名(famous)" },
    { word: "be fit for", meaning: "适合(fit)" },
    { word: "be good for", meaning: "对…有好处(good)" },
    { word: "be grateful for", meaning: "对…感激(grateful)" },
    { word: "be hungry for", meaning: "渴望(hungry)" },
    { word: "be late for", meaning: "迟到(late)" },
    { word: "be ready for", meaning: "为…做好准备(ready)" },
    { word: "be absent from", meaning: "缺席(absent)" },
    { word: "be different from", meaning: "与…不同(different)" },
    { word: "be concerned in", meaning: "参与；与…有关(concerned)" },
    { word: "be disappointed in", meaning: "对…失望(disappointed)" },
    { word: "be engaged in", meaning: "从事于；忙于(engaged)" },
    { word: "be experienced in", meaning: "在…方面有经验(experienced)" },
    { word: "be expert in", meaning: "在…方面精通(expert)" },
    { word: "be fortunate in", meaning: "在…方面幸运(fortunate)" },
    { word: "be honest in", meaning: "在…方面诚实(honest)" },
    { word: "be afraid of", meaning: "害怕(afraid)" },
    { word: "be ashamed of", meaning: "为…感到羞愧(ashamed)" },
    { word: "be aware of", meaning: "意识到(aware)" },
    { word: "be capable of", meaning: "能够；有…能力(capable)" },
    { word: "be careful of", meaning: "小心；留意(careful)" },
    { word: "be fond of", meaning: "喜欢(fond)" },
    { word: "be free of", meaning: "没有；摆脱(free)" },
    { word: "be blind to doing sth.", meaning: "对…视而不见(blind)" },
    { word: "be sorry for", meaning: "为…感到抱歉(sorry)" },
    { word: "be suitable for", meaning: "适合(suitable)" },
    { word: "be thankful for", meaning: "对…感恩(thankful)" },
    { word: "be far from", meaning: "离…远；远非(far)" },
    { word: "be free from", meaning: "免受；没有(free)" },
    { word: "be interested in", meaning: "对…感兴趣(interested)" },
    { word: "be lacking in", meaning: "缺乏(lacking)" },
    { word: "be rich in", meaning: "富含(rich)" },
    { word: "be skillful in", meaning: "在…方面熟练(skillful)" },
    { word: "be successful in", meaning: "在…方面成功(successful)" },
    { word: "be weak in", meaning: "在…方面薄弱(weak)" },
    { word: "be full of", meaning: "充满(full)" },
    { word: "be glad of", meaning: "为…高兴(glad)" },
    { word: "be proud of", meaning: "为…骄傲(proud)" },
    { word: "be short of", meaning: "短缺(short)" },
    { word: "be sick of", meaning: "对…厌烦(sick)" },
    { word: "be sure of", meaning: "对…确信(sure)" },
    { word: "be tired of", meaning: "对…厌倦(tired)" },
    { word: "be close to doing sth.", meaning: "靠近；接近(close)" },
    { word: "be cruel to doing sth.", meaning: "对…残酷(cruel)" },
    { word: "be devoted to doing sth.", meaning: "致力于；忠诚于(devoted)" },
    { word: "be equal to doing sth.", meaning: "等于；胜任(equal)" },
    { word: "be familiar to doing sth.", meaning: "为…所熟悉(familiar)" },
    { word: "be harmful to doing sth.", meaning: "对…有害(harmful)" },
    { word: "be important to doing sth.", meaning: "对…重要(important)" },
    { word: "be open to doing sth.", meaning: "对…开放；易受…影响(open)" },
    { word: "be opposed to doing sth.", meaning: "反对(opposed)" },
    { word: "be polite to doing sth.", meaning: "对…有礼貌(polite)" },
    { word: "be rude to doing sth.", meaning: "对…粗鲁(rude)" },
    { word: "be true to doing sth.", meaning: "忠实于(true)" },
    { word: "be useful to doing sth.", meaning: "对…有用(useful)" },
    { word: "be angry with", meaning: "生…的气(angry)" },
    { word: "be bored with", meaning: "对…厌烦(bored)" },
    { word: "be busy with", meaning: "忙于…(busy)" },
    { word: "be careful with", meaning: "小心；谨慎对待(careful)" },
    { word: "be concerned with", meaning: "与…有关；涉及(concerned)" },
    { word: "be content with", meaning: "对…满意(content)" },
    { word: "be disappointed with", meaning: "对…失望(disappointed)" },
    { word: "be familiar with", meaning: "熟悉…(familiar)" },
    { word: "be honest with", meaning: "对…诚实(honest)" },
    { word: "be patient with", meaning: "对…有耐心(patient)" },
    { word: "be pleased with", meaning: "对…满意(pleased)" },
    { word: "be popular with", meaning: "受…欢迎(popular)" },
    { word: "be satisfied with", meaning: "对…满意(satisfied)" },
    { word: "be strict with", meaning: "对…严格(strict)" },
    { word: "break away", meaning: "脱离；逃脱(break)" },
    { word: "break down", meaning: "出故障；分解；垮掉(break)" },
    { word: "break into", meaning: "闯入；突然开始做 (break)" },
    { word: "break in", meaning: "打断；闯入（不及物，常指强行进入屋内，偏口语）(break)" },
    { word: "break off", meaning: "折断；中断(break)" },
    { word: "break out", meaning: "爆发；突发(break)" },
    { word: "break over", meaning: "（暴风雨等）突然降临；席卷(break)" },
    { word: "break through", meaning: "突破；突围(break)" },
    { word: "break up", meaning: "分手；打碎；结束(break)" },
    { word: "bring about", meaning: "导致；引起(bring)" },
    { word: "bring back", meaning: "带回；使回忆起(bring)" },
    { word: "bring down", meaning: "降低；打倒(bring)" },
    { word: "bring in", meaning: "引进；带来（收入等）(bring)" },
    { word: "bring into", meaning: "使进入；使卷入(bring)" },
    { word: "catch fire", meaning: "着火(catch)" },
    { word: "catch sight of", meaning: "看到；瞥见(catch)" },
    { word: "catch up with", meaning: "赶上(catch)" },
    { word: "catch up", meaning: "赶上；追上(catch)" },
    { word: "come back", meaning: "回来；恢复(come)" },
    { word: "come down", meaning: "下降；下来(come)" },
    { word: "come from", meaning: "来自(come)" },
    { word: "come in", meaning: "进来(come)" },
    { word: "come into", meaning: "进入；得到(come)" },
    { word: "come off", meaning: "脱落；成功(come)" },
    { word: "come on", meaning: "快点；来吧；开始(come)" },
    { word: "come out", meaning: "出来；出版；结果是(come)" },
    { word: "come over", meaning: "过来；顺便来访(come)" },
    { word: "come true", meaning: "实现(come)" },
    { word: "come up", meaning: "走近；被提出(come)" },
    { word: "cut across", meaning: "抄近路穿过(cut)" },
    { word: "cut away", meaning: "切掉；砍掉(cut)" },
    { word: "cut down", meaning: "削减；砍倒(cut)" },
    { word: "cut into", meaning: "切入；打断(cut)" },
    { word: "cut in", meaning: "插嘴；超车(cut)" },
    { word: "cut off", meaning: "切断；隔绝(cut)" },
    { word: "cut out", meaning: "剪下；删除(cut)" },
    { word: "cut through", meaning: "抄近路穿过；穿透(cut)" },
    { word: "die from", meaning: "死于（外部原因，如事故、灾害）(die)" },
    { word: "die of", meaning: "死于（内部原因，如疾病、饥饿）(die)" },
    { word: "die out", meaning: "灭绝(die)" },
    { word: "do a deal with", meaning: "与…做交易(do)" },
    { word: "do a good job", meaning: "干得好(do)" },
    { word: "do business", meaning: "做生意(do)" },
    { word: "break down", meaning: "出故障；分解；垮掉(break)" },
    { word: "bring down", meaning: "降低；打倒(bring)" },
    { word: "burn down", meaning: "烧毁(burn)" },
    { word: "calm down", meaning: "平静下来(calm)" },
    { word: "come down", meaning: "下降；下来(come)" },
    { word: "pass down", meaning: "传承；流传(pass)" },
    { word: "drive away", meaning: "赶走；驾车离开(drive)" },
    { word: "drive home", meaning: "把…讲清楚；开车回家(drive)" },
    { word: "drive off", meaning: "赶走；驾车离去(drive)" },
    { word: "drop a line", meaning: "写封短信(drop)" },
    { word: "drop back", meaning: "退后；落后(drop)" },
    { word: "drop behind", meaning: "落后(drop)" },
    { word: "drop down", meaning: "落下；卧倒(drop)" },
    { word: "fall apart", meaning: "破裂；散架(fall)" },
    { word: "fall asleep", meaning: "入睡(fall)" },
    { word: "do the dishes", meaning: "洗餐具(do)" },
    { word: "do well in", meaning: "在…方面做得好(do)" },
    { word: "do with", meaning: "处理；对付(do)" },
    { word: "put down", meaning: "放下；镇压(put)" },
    { word: "settle down", meaning: "定居；平静下来(settle)" },
    { word: "slow down", meaning: "减速(slow)" },
    { word: "take down", meaning: "记下；拿下(take)" },
    { word: "tear down", meaning: "拆除；撕掉(tear)" },
    { word: "turn down", meaning: "拒绝；调低(turn)" },
    { word: "drive on", meaning: "继续开车(drive)" },
    { word: "drive out", meaning: "驱赶；开车外出(drive)" },
    { word: "drop litter", meaning: "扔垃圾(drop)" },
    { word: "drop off", meaning: "下降；让…下车(drop)" },
    { word: "drop out", meaning: "退学；退出(drop)" },
    { word: "drop over", meaning: "顺便来访(drop)" },
    { word: "drop to doing sth.", meaning: "下降到(drop)" },
    { word: "fall behind", meaning: "落后(fall)" },
    { word: "fall down", meaning: "跌倒；倒塌(fall)" },
    { word: "fall in love", meaning: "坠入爱河(fall)" },
    { word: "fall into", meaning: "落入；陷入(fall)" },
    { word: "apply for", meaning: "申请(apply)" },
    { word: "ask for", meaning: "请求；要求(ask)" },
    { word: "beg for", meaning: "乞求(beg)" },
    { word: "call for", meaning: "需要；要求；呼吁(call)" },
    { word: "care for", meaning: "照顾；喜欢(care)" },
    { word: "hope for", meaning: "希望；期待(hope)" },
    { word: "hunt for", meaning: "搜寻；寻找(hunt)" },
    { word: "date from", meaning: "追溯到(date)" },
    { word: "die from", meaning: "死于（外部原因，如事故、灾难等）(die)" },
    { word: "differ from", meaning: "与…不同(differ)" },
    { word: "hear from", meaning: "收到…的来信(hear)" },
    { word: "keep from", meaning: "阻止；避免(keep)" },
    { word: "fall off", meaning: "从…掉落；减少(fall)" },
    { word: "long for", meaning: "渴望(long)" },
    { word: "look for", meaning: "寻找(look)" },
    { word: "run for", meaning: "竞选；跑去取(run)" },
    { word: "search for", meaning: "搜寻；查找(search)" },
    { word: "seek for", meaning: "寻找；追求(seek)" },
    { word: "stand for", meaning: "代表；支持；容忍(stand)" },
    { word: "wait for", meaning: "等待(wait)" },
    { word: "wish for", meaning: "盼望；企求(wish)" },
    { word: "learn from", meaning: "向…学习(learn)" },
    { word: "result from", meaning: "由…造成(result)" },
    { word: "separate from", meaning: "与…分开(separate)" },
    { word: "suffer from", meaning: "遭受；患…病(suffer)" },
    { word: "get across", meaning: "使被理解；通过(get)" },
    { word: "get along", meaning: "进展；相处(get)" },
    { word: "get away", meaning: "离开；逃脱(get)" },
    { word: "get down", meaning: "下来；写下(get)" },
    { word: "get home", meaning: "到家(get)" },
    { word: "get in", meaning: "进入；收获；当选(get)" },
    { word: "get off", meaning: "下车；脱下；动身(get)" },
    { word: "get on", meaning: "上车；进展；相处(get)" },
    { word: "get out of", meaning: "从…出来；逃避(get)" },
    { word: "get out", meaning: "出去；泄露(get)" },
    { word: "get over", meaning: "克服；恢复(get)" },
    { word: "get rid of", meaning: "摆脱；除去(get)" },
    { word: "get through", meaning: "通过；完成；接通（电话）(get)" },
    { word: "get to doing sth.", meaning: "到达(get)" },
    { word: "get together", meaning: "聚会；相聚(get)" },
    { word: "get up", meaning: "起床；起立(get)" },
    { word: "get used to doing sth.", meaning: "习惯于(get)" },
    { word: "give a talk", meaning: "做报告；演讲(give)" },
    { word: "give away", meaning: "赠送；泄露(give)" },
    { word: "give back", meaning: "归还；恢复(give)" },
    { word: "give in", meaning: "屈服；让步(give)" },
    { word: "give off", meaning: "发出（光、热、气味等）(give)" },
    { word: "give out", meaning: "分发；公布；耗尽(give)" },
    { word: "give sb. a call", meaning: "给某人打电话(give)" },
    { word: "give sb. a hand", meaning: "帮某人一把(give)" },
    { word: "give up", meaning: "放弃；投降(give)" },
    { word: "give way", meaning: "让路；让步(give)" },
    { word: "give way to doing sth.", meaning: "给…让路；被…取代(give)" },
    { word: "go after", meaning: "追逐；追求(go)" },
    { word: "go against", meaning: "违背；与…作对(go)" },
    { word: "go ahead", meaning: "前进；开始；继续(go)" },
    { word: "go away", meaning: "离开；消失(go)" },
    { word: "go back", meaning: "回去；追溯(go)" },
    { word: "go by", meaning: "（时间等）过去；经过(go)" },
    { word: "go down", meaning: "下降；下沉；被记下(go)" },
    { word: "go in for", meaning: "参加；爱好(go)" },
    { word: "go on", meaning: "继续；发生(go)" },
    { word: "go out", meaning: "出去；熄灭(go)" },
    { word: "go over", meaning: "复习；仔细检查(go)" },
    { word: "go round", meaning: "四处走动；足够分配(go)" },
    { word: "go through", meaning: "经历；通过；仔细查看(go)" },
    { word: "go up", meaning: "上升；增长(go)" },
    { word: "go wrong", meaning: "出毛病；出错(go)" },
    { word: "hand down", meaning: "把…传下去(hand)" },
    { word: "hand in hand", meaning: "手拉手；密切关联(hand)" },
    { word: "hand in", meaning: "上交；提交(hand)" },
    { word: "hand out", meaning: "分发；散发(hand)" },
    { word: "hand over", meaning: "移交；交出(hand)" },
    { word: "hang up", meaning: "挂断（电话）；挂起(hang)" },
    { word: "hang down", meaning: "垂下；耷拉(hang)" },
    { word: "hang out", meaning: "闲逛；晾晒(hang)" },
    { word: "have a cold", meaning: "感冒(have)" },
    { word: "have a fever", meaning: "发烧(have)" },
    { word: "have a gift for", meaning: "有…的天赋(have)" },
    { word: "have a good time", meaning: "玩得开心(have)" },
    { word: "have a meal", meaning: "吃饭(have)" },
    { word: "have a party", meaning: "举办派对(have)" },
    { word: "hear about", meaning: "听说(hear)" },
    { word: "hear from", meaning: "收到…的来信(hear)" },
    { word: "hold back", meaning: "阻挡；抑制；退缩(hold)" },
    { word: "hold on", meaning: "不挂断电话；坚持(hold)" },
    { word: "break in", meaning: "闯入；打断（谈话等）(break)" },
    { word: "bring in", meaning: "引进；带来；赚取(bring)" },
    { word: "call in", meaning: "召集；打电话来；顺便拜访(call)" },
    { word: "cut in", meaning: "插嘴；超车(cut)" },
    { word: "drop in", meaning: "顺便走访(drop)" },
    { word: "fill in", meaning: "填写；填补(fill)" },
    { word: "get in", meaning: "进入；收获；当选(get)" },
    { word: "in a hurry", meaning: "匆忙地(hurry)" },
    { word: "in a word", meaning: "总而言之(word)" },
    { word: "in all", meaning: "总共(all)" },
    { word: "have a rest", meaning: "休息(rest)" },
    { word: "have classes", meaning: "上课(classes)" },
    { word: "have fun", meaning: "玩得开心(fun)" },
    { word: "have sports", meaning: "进行体育运动(sports)" },
    { word: "have to do sth.", meaning: "必须；不得不(to)" },
    { word: "have..in common", meaning: "有…共同之处(common)" },
    { word: "hear of", meaning: "听说(hear)" },
    { word: "hold up", meaning: "举起；阻挡(hold)" },
    { word: "hold with", meaning: "赞成；同意(hold)" },
    { word: "give in", meaning: "屈服；让步(give)" },
    { word: "hand in", meaning: "上交；提交(hand)" },
    { word: "join in", meaning: "参加(join)" },
    { word: "persist in", meaning: "坚持(persist)" },
    { word: "result in", meaning: "导致(result)" },
    { word: "succeed in", meaning: "在…方面成功(succeed)" },
    { word: "take in", meaning: "吸收；理解；欺骗(take)" },
    { word: "in fact", meaning: "事实上(fact)" },
    { word: "in front of", meaning: "在…前面(front)" },
    { word: "in line", meaning: "成直线；排队(line)" },
    { word: "in no time", meaning: "立刻；很快(time)" },
    { word: "in class", meaning: "在上课(class)" },
    { word: "in order to do sth.", meaning: "为了(order)" },
    { word: "in hospital", meaning: "住院(hospital)" },
    { word: "in order", meaning: "整齐；按顺序(order)" },
    { word: "in office", meaning: "在职；执政(office)" },
    { word: "in public", meaning: "公开地；在公众场合(public)" },
    { word: "in place of", meaning: "代替(place)" },
    { word: "in surprise", meaning: "惊讶地(surprise)" },
    { word: "in prison", meaning: "在狱中(prison)" },
    { word: "in the day", meaning: "在白天(day)" },
    { word: "in red", meaning: "穿着红色衣服(red)" },
    { word: "in the end", meaning: "最后；终于(end)" },
    { word: "in secret", meaning: "秘密地(secret)" },
    { word: "in the middle of", meaning: "在…中间(middle)" },
    { word: "in the bed", meaning: "在床上(bed)" },
    { word: "in the street", meaning: "在街上(street)" },
    { word: "in the class", meaning: "在班级里(class)" },
    { word: "in the sun", meaning: "在阳光下(sun)" },
    { word: "in the hospital", meaning: "在医院里(hospital)" },
    { word: "in time", meaning: "及时(time)" },
    { word: "in the office", meaning: "在办公室里(office)" },
    { word: "in trouble", meaning: "处于困境中(trouble)" },
    { word: "in the place of", meaning: "代替(place)", },
    { word: "in turn", meaning: "轮流；依次(turn)" },
    { word: "in the prison", meaning: "在监狱里(prison)" },
    { word: "in bed", meaning: "在床上；卧床(bed)" },
    { word: "in the red", meaning: "赤字；亏损(red)" },
    { word: "in case of", meaning: "假使；万一(case)" },
    { word: "in the secret", meaning: "知道内情的；参与秘密的(secret)" },
    { word: "in aid of", meaning: "为了帮助；以助(aid)" },
    { word: "in behalf of", meaning: "为了…的利益；代表(behalf)" },
    { word: "in case of", meaning: "以防；万一(case)" },
    { word: "in charge of", meaning: "负责；主管(charge)" },
    { word: "in defence of", meaning: "为…辩护；保卫(defence)" },
    { word: "in explanation of", meaning: "解释；说明(explanation)" },
    { word: "in face of", meaning: "面对(face)" },
    { word: "in favour of", meaning: "支持；赞成(favour)" },
    { word: "in honor of", meaning: "为了纪念；向…表示敬意(honor)" },
    { word: "in memory of", meaning: "纪念(memory)" },
    { word: "in need of", meaning: "需要(need)" },
    { word: "in place of", meaning: "代替(place)" },
    { word: "in possession of", meaning: "拥有；占有(possession)" },
    { word: "in praise of", meaning: "赞扬；歌颂(praise)" },
    { word: "in respect of", meaning: "关于；就…而言(respect)" },
    { word: "in search of", meaning: "寻找；搜寻(search)" },
    { word: "in sight of", meaning: "能看见(sight)" },
    { word: "in spite of", meaning: "尽管；不管(spite)" },
    { word: "in support of", meaning: "支持；拥护(support)" },
    { word: "in view of", meaning: "鉴于；考虑到(view)" },
    { word: "keep away", meaning: "远离(keep)" },
    { word: "keep healthy", meaning: "保持健康(keep)" },
    { word: "keep in mind", meaning: "牢记(mind)" },
    { word: "keep in touch", meaning: "保持联系(touch)" },
    { word: "keep on", meaning: "继续；反复地做(keep)" },
    { word: "keep out", meaning: "不让…进入；挡住(keep)" },
    { word: "keep pace", meaning: "跟上步伐(pace)" },
    { word: "keep to oneself", meaning: "不与他人交往；保守秘密(oneself)" },
    { word: "keep track", meaning: "追踪；了解动态(track)" },
    { word: "keep up", meaning: "保持；继续；不低落(keep)" },
    { word: "keep up with", meaning: "跟上；不落后于(keep)" },
    { word: "knock at", meaning: "敲（门、窗等）(knock)" },
    { word: "knock down", meaning: "撞倒；拆除；降低(knock)" },
    { word: "knock into", meaning: "撞上；偶然碰到(knock)" },
    { word: "knock off", meaning: "敲掉；停止工作；降价(knock)" },
    { word: "knock out", meaning: "敲空；击昏；淘汰(knock)" },
    { word: "knock over", meaning: "打翻；撞倒(knock)" },
    { word: "annual leave", meaning: "年假(annual)" },
    { word: "leave a message", meaning: "留言(message)" },
    { word: "leave alone", meaning: "不打扰；听其自然(leave)" },
    { word: "leave apart", meaning: "把…分开(leave)" },
    { word: "leave away", meaning: "离开；缺席(leave)" },
    { word: "leave behind", meaning: "留下；遗留；把…抛在后面(leave)" },
    { word: "leave for", meaning: "动身去；前往(leave)" },
    { word: "leave from", meaning: "从…离开(leave)" },
    { word: "leave home", meaning: "离家(leave)" },
    { word: "leave off", meaning: "停止；中断；省去(leave)" },
    { word: "leave out", meaning: "遗漏；省略；不考虑(leave)" },
    { word: "on leave", meaning: "休假(leave)" },
    { word: "sick leave", meaning: "病假(sick)" },
    { word: "look after", meaning: "照顾；照料(look)" },
    { word: "look ahead", meaning: "展望未来；向前看(look)" },
    { word: "look around", meaning: "环顾；四处看(look)" },
    { word: "look back", meaning: "回顾；回头看(look)" },
    { word: "look down upon", meaning: "看不起；轻视(look)" },
    { word: "look down", meaning: "向下看；俯视(look)" },
    { word: "look for", meaning: "寻找(look)" },
    { word: "look forward to doing", meaning: "盼望做某事(look)" },
    { word: "look into", meaning: "调查；窥视(look)" },
    { word: "look like", meaning: "看起来像(look)" },
    { word: "look on", meaning: "旁观；看待(look)" },
    { word: "look out", meaning: "当心；向外看(look)" },
    { word: "look over", meaning: "检查；查看(look)" },
    { word: "look through", meaning: "浏览；看穿(look)" },
    { word: "make a decision", meaning: "做决定(make)" },
    { word: "make a living", meaning: "谋生(make)" },
    { word: "make a mistake", meaning: "犯错误(make)" },
    { word: "make an appointment", meaning: "预约；约会(make)" },
    { word: "make clear", meaning: "阐明；弄清楚(make)" },
    { word: "make friends with", meaning: "与…交朋友(make)" },
    { word: "make full use of", meaning: "充分利用(make)" },
    { word: "move around", meaning: "走来走去；四处移动(move)" },
    { word: "move against", meaning: "向…移动；反对(move)" },
    { word: "move aside", meaning: "移到一边(move)" },
    { word: "move away", meaning: "搬走；离开(move)" },
    { word: "move back", meaning: "向后移动；退缩(move)" },
    { word: "approve of", meaning: "赞成；认可(approve)" },
    { word: "complain of", meaning: "抱怨；诉苦(complain)" },
    { word: "consist of", meaning: "由…组成；包括(consist)" },
    { word: "die of", meaning: "死于（疾病、饥饿等内在原因）(die)" },
    { word: "break out", meaning: "爆发；突发(break)" },
    { word: "bring out", meaning: "使显现；出版；生产(bring)" },
    { word: "look to doing sth.", meaning: "注意；指望；照看(look)" },
    { word: "look up to doing sth.", meaning: "尊敬；敬仰(look)" },
    { word: "look up", meaning: "查阅；向上看；改善(look)" },
    { word: "make it possible", meaning: "使…成为可能(make)" },
    { word: "make it", meaning: "成功；赶上；做到(make)" },
    { word: "make out", meaning: "辨认出；理解；写出(make)" },
    { word: "make sense", meaning: "有意义；讲得通(make)" },
    { word: "make sure", meaning: "确保；查明(make)" },
    { word: "make up for", meaning: "弥补；补偿(make)" },
    { word: "make up", meaning: "组成；编造；化妆(make)" },
    { word: "move off", meaning: "离开；出发(move)" },
    { word: "move on", meaning: "继续前进；往前走；更换话题(move)" },
    { word: "move out", meaning: "搬出；搬走(move)" },
    { word: "move in", meaning: "搬进；迁入(move)" },
    { word: "move to doing sth.", meaning: "搬到；移至(move)" },
    { word: "dream of", meaning: "梦想；梦见(dream)" },
    { word: "speak of", meaning: "谈到；说起(speak)" },
    { word: "talk of", meaning: "谈论；谈及(talk)" },
    { word: "think of", meaning: "想起；考虑；认为(think)" },
    { word: "burst out", meaning: "突然…起来(burst)" },
    { word: "carry out", meaning: "执行；实行(carry)" },
    { word: "come out", meaning: "出来；出版；结果是(come)" },
    { word: "figure out", meaning: "算出；想出；理解(figure)" },
    { word: "pick out", meaning: "挑选出；辨认出(pick)" },
    { word: "find out", meaning: "查明；找出(find)" },
    { word: "point out", meaning: "指出(point)" },
    { word: "put out", meaning: "扑灭；熄灭；生产(put)" },
    { word: "give out", meaning: "分发；公布；耗尽(give)" },
    { word: "go out", meaning: "出去；熄灭(go)" },
    { word: "run out", meaning: "用完；耗尽(run)" },
    { word: "help out", meaning: "帮助解决难题；帮忙(help)" },
    { word: "send out", meaning: "发送；派遣(send)" },
    { word: "hold out", meaning: "伸出；坚持；维持(hold)" },
    { word: "set out", meaning: "出发；开始；陈述(set)" },
    { word: "keep out", meaning: "不让…进入；挡住(keep)" },
    { word: "speak out", meaning: "大声说；畅所欲言(speak)" },
    { word: "leave out", meaning: "遗漏；省略；不考虑(leave)" },
    { word: "try out", meaning: "试用；试验(try)" },
    { word: "let out", meaning: "放出；泄露(let)" },
    { word: "turn out", meaning: "结果是；生产；关掉(turn)" },
    { word: "look out", meaning: "当心；向外看(look)" },
    { word: "wear out", meaning: "穿破；耗尽(wear)" },
    { word: "hand out", meaning: "分发；散发(hand)" },
    { word: "work out", meaning: "算出；解决；锻炼(work)" },
    { word: "fall over", meaning: "跌倒；摔倒(fall)" },
    { word: "get over", meaning: "克服；恢复(get)" },
    { word: "go over", meaning: "复习；仔细检查(go)" },
    { word: "look over", meaning: "检查；查看(look)" },
    { word: "roll over", meaning: "翻滚；翻身(roll)" },
    { word: "run over", meaning: "碾过；匆匆看一遍(run)" },
    { word: "take over", meaning: "接管；接收(take)" },
    { word: "think over", meaning: "仔细考虑(think)" },
    { word: "turn over", meaning: "翻转；移交(turn)" },
    { word: "watch over", meaning: "看守；监视(watch)" },
    { word: "pass along", meaning: "沿…走；传递(pass)" },
    { word: "pass away", meaning: "去世；消失(pass)" },
    { word: "pass by", meaning: "经过；路过(pass)" },
    { word: "pass down", meaning: "传承；流传(pass)" },
    { word: "pass on", meaning: "传递；继续(pass)" },
    { word: "pass over", meaning: "忽略；不考虑(pass)" },
    { word: "pass through", meaning: "穿过；经历(pass)" },
    { word: "pick off", meaning: "摘掉；采下(pick)" },
    { word: "pick out", meaning: "挑选出；辨认出(pick)" },
    { word: "pick sb.up", meaning: "接某人(pick)" },
    { word: "pick up", meaning: "捡起；（偶然）学会；搭载(pick)" },
    { word: "set off", meaning: "出发；引爆(set)" },
    { word: "set about", meaning: "着手做；开始(set)" },
    { word: "set out", meaning: "出发；开始；陈述(set)" },
    { word: "set apart", meaning: "使与众不同；留出(set)" },
    { word: "set aside", meaning: "留出；搁置(set)" },
    { word: "set up", meaning: "建立；设立(set)" },
    { word: "set down", meaning: "记下；放下(set)" },
    { word: "on show", meaning: "在展出(show)" },
    { word: "show sb.around", meaning: "带某人参观(show)" },
    { word: "show in", meaning: "领入(show)" },
    { word: "show up", meaning: "出现；露面(show)" },
    { word: "show off", meaning: "炫耀(show)" },
    { word: "take action", meaning: "采取行动(take)" },
    { word: "take it easy", meaning: "别紧张；放松点(take)" },
    { word: "take after", meaning: "（外貌、性格等）与…相像(take)" },
    { word: "take off", meaning: "起飞；脱下；突然成功(take)" },
    { word: "take as", meaning: "把…当作(take)" },
    { word: "take on", meaning: "承担；呈现；雇佣(take)" },
    { word: "take away", meaning: "拿走；减去(take)" },
    { word: "take one's place", meaning: "取代某人；就座(take)" },
    { word: "take back", meaning: "收回；退回；使回忆起(take)" },
    { word: "take out", meaning: "取出；拔掉；带…出去(take)" },
    { word: "take care of", meaning: "照顾；处理(take)" },
    { word: "take over", meaning: "接管；接收(take)" },
    { word: "take care", meaning: "小心；注意(take)" },
    { word: "take part in", meaning: "参加(take)" },
    { word: "take charge of", meaning: "负责；掌管(take)" },
    { word: "take place", meaning: "发生；举行(take)" },
    { word: "take down", meaning: "记下；拆除；拿下(take)" },
    { word: "take the place of", meaning: "代替(take)" },
    { word: "take in", meaning: "吸收；理解；欺骗(take)" },
    { word: "talk apart", meaning: "拆开谈；分开讨论(talk)" },
    { word: "take up", meaning: "占据；开始从事；拿起(take)" },
    { word: "talk of", meaning: "谈论；提及(talk)" },
    { word: "talk with", meaning: "与…交谈(talk)" },
    { word: "talk over", meaning: "详细讨论；商议(talk)" },
    { word: "tell A from B", meaning: "区分A和B(tell)" },
    { word: "tell a lie", meaning: "说谎(tell)" },
    { word: "tell about", meaning: "讲述；谈及(tell)" },
    { word: "tell one's fortune", meaning: "给某人算命(tell)" },
    { word: "tell sb. about sth.", meaning: "告诉某人某事(tell)" },
    { word: "think about", meaning: "考虑；思考(think)" },
    { word: "think back", meaning: "回想；回忆(think)" },
    { word: "think deeply", meaning: "深入思考(think)" },
    { word: "think highly of", meaning: "高度评价(think)" },
    { word: "think of", meaning: "想起；考虑；认为(think)" },
    { word: "tell sb. to do sth.", meaning: "告诉某人做某事(tell)" },
    { word: "tell the truth", meaning: "说实话(tell)" },
    { word: "think out", meaning: "想出；仔细考虑(think)" },
    { word: "think over", meaning: "仔细考虑(think)" },
    { word: "think twice", meaning: "三思而后行(think)" },
    { word: "think up", meaning: "想出；虚构(think)" },
    { word: "throw at", meaning: "向…扔去(throw)" },
    { word: "throw away", meaning: "扔掉；抛弃(throw)" },
    { word: "in no time", meaning: "立刻；很快(time)" },
    { word: "in one’s time", meaning: "在某人的时代(time)" },
    { word: "in time", meaning: "及时；迟早(time)" },
    { word: "on time", meaning: "准时(time)" },
    { word: "for the first time", meaning: "第一次(time)" },
    { word: "for the time being", meaning: "暂时；眼下(time)" },
    { word: "from time to time", meaning: "不时；偶尔(time)" },
    { word: "have a good time", meaning: "玩得开心(time)" },
    { word: "have a rough time", meaning: "过得艰难(time)" },
    { word: "in one's own time", meaning: "在自己的时间里；有空时(time)" },
    { word: "in times to come", meaning: "在未来的日子里(time)" },
    { word: "make time", meaning: "腾出时间(time)" },
    { word: "once upon a time", meaning: "从前(time)" },
    { word: "throw back", meaning: "扔回；回顾(throw)" },
    { word: "ahead of time", meaning: "提前(time)" },
    { word: "all the time", meaning: "一直；始终(time)" },
    { word: "at a time", meaning: "一次；每次(time)" },
    { word: "at all times", meaning: "随时；总是(time)" },
    { word: "at any time", meaning: "在任何时候(time)" },
    { word: "at no time", meaning: "绝不；在任何时候都不(time)" },
    { word: "at one time", meaning: "曾经；一度(time)" },
    { word: "at the time of", meaning: "在…的时候(time)" },
    { word: "at times", meaning: "有时；偶尔(time)" },
    { word: "by the time", meaning: "到…的时候(time)" },
    { word: "by this time", meaning: "到这时(time)" },
    { word: "every time", meaning: "每次；每当(time)" },
    { word: "throw down", meaning: "扔下；推翻(throw)" },
    { word: "throw in", meaning: "扔进；额外奉送(throw)" },
    { word: "add to doing sth.", meaning: "增加；增添(add)" },
    { word: "agree to doing sth.", meaning: "同意；答应(agree)" },
    { word: "attend to doing sth.", meaning: "照料；处理；专心于(attend)" },
    { word: "belong to doing sth.", meaning: "属于(belong)" },
    { word: "bring to doing sth.", meaning: "使恢复知觉；使停下(bring)" },
    { word: "come to doing sth.", meaning: "苏醒；总计；达到(come)" },
    { word: "compare..to doing sth.", meaning: "把…比作(compare)" },
    { word: "devote..to doing sth.", meaning: "致力于；把…奉献给(devote)" },
    { word: "get to do sth.", meaning: "开始；着手(get)" },
    { word: "get to doing sth.", meaning: "到达；开始；着手(get)" },
    { word: "lead to doing sth.", meaning: "导致；通向(lead)" },
    { word: "try again", meaning: "再试一次(try)" },
    { word: "try doing sth.", meaning: "尝试做某事(try)" },
    { word: "try on", meaning: "试穿(try)" },
    { word: "try one's best", meaning: "尽某人最大努力(try)" },
    { word: "turn back", meaning: "往回走；翻回；折转(turn)" },
    { word: "turn down", meaning: "拒绝；调低（音量等）(turn)" },
    { word: "turn into", meaning: "变成；进入(turn)" },
    { word: "turn left", meaning: "向左转(turn)" },
    { word: "turn off", meaning: "关掉（电器、水源等）(turn)" },
    { word: "turn on", meaning: "打开（电器、水源等）(turn)" },
    { word: "out of time", meaning: "不合时宜；没时间(time)" },
    { word: "object to doing sth.", meaning: "反对(object)" },
    { word: "point to doing sth.", meaning: "指向；表明(point)" },
    { word: "refer to doing sth.", meaning: "参考；涉及；指的是(refer)" },
    { word: "relate to doing sth.", meaning: "与…有关；涉及(relate)" },
    { word: "reply to doing sth.", meaning: "回复；答复(reply)" },
    { word: "see to doing sth.", meaning: "照料；处理；负责(see)" },
    { word: "stick to doing sth.", meaning: "坚持；粘住(stick)" },
    { word: "hold to doing sth.", meaning: "坚持；紧握(hold)" },
    { word: "keep to doing sth.", meaning: "遵守；坚持(keep)" },
    { word: "supply..to doing sth.", meaning: "把…供给(supply)" },
    { word: "turn to doing sth.", meaning: "转向；求助于(turn)" },
    { word: "write to doing sth.", meaning: "写信给(write)" },
    { word: "try one's luck", meaning: "碰碰运气(try)" },
    { word: "try out", meaning: "试用；试验(try)" },
    { word: "try over", meaning: "排练；试演(try)" },
    { word: "try to do sth.", meaning: "试图做某事(try)" },
    { word: "turn out", meaning: "结果是；生产；关掉(turn)" },
    { word: "turn over", meaning: "翻转；移交；仔细考虑(turn)" },
    { word: "turn right", meaning: "向右转(turn)" },
    { word: "turn round", meaning: "转身；转变；使好转(turn)" },
    { word: "turn up", meaning: "出现；调高（音量等）(turn)" },
    { word: "bring up", meaning: "养育；提出；呕吐(bring)" },
    { word: "call up", meaning: "打电话；唤起；征召(call)" },
    { word: "cheer up", meaning: "使高兴；振作起来(cheer)" },
    { word: "fill up", meaning: "装满；填满(fill)" },
    { word: "fix up", meaning: "修理；安排；解决(fix)" },
    { word: "go up", meaning: "上升；上涨(go)" },
    { word: "grow up", meaning: "长大；成长(grow)" },
    { word: "hurry up", meaning: "赶快；快点(hurry)" },
    { word: "look up", meaning: "查阅；向上看；改善(look)" },
    { word: "pick up", meaning: "捡起；（偶然）学会；搭载(pick)" },
    { word: "put up", meaning: "张贴；举起；建造(put)" },
    { word: "save up", meaning: "储蓄；积攒(save)" },
    { word: "set up", meaning: "建立；设立(set)" },
    { word: "show up", meaning: "出现；露面(show)" },
    { word: "shut up", meaning: "闭嘴；关上(shut)" },
    { word: "sit up", meaning: "熬夜；端坐(sit)" },
    { word: "speak up", meaning: "大声说；畅所欲言(speak)" },
    { word: "stay up", meaning: "熬夜；不睡觉(stay)" },
    { word: "think up", meaning: "想出；虚构(think)" },
    { word: "tidy up", meaning: "整理；收拾(tidy)" },
    { word: "turn up", meaning: "出现；调高（音量等）(turn)" },
    { word: "imagine doing sth.", meaning: "想象做某事(imagine)" },
    { word: "mind doing sth.", meaning: "介意做某事(mind)" },
    { word: "practice doing sth.", meaning: "练习做某事(practice)" },
    { word: "prevent doing sth.", meaning: "阻止做某事(prevent)" },
    { word: "put off doing sth.", meaning: "推迟做某事(put)" },
    { word: "risk doing sth.", meaning: "冒险做某事(risk)" },
    { word: "consider doing sth.", meaning: "考虑做某事(consider)" },
    { word: "enjoy doing sth.", meaning: "喜欢做某事(enjoy)" },
    { word: "escape doing sth.", meaning: "逃脱做某事(escape)" },
    { word: "finish doing sth.", meaning: "完成做某事(finish)" },
    { word: "forbid doing sth.", meaning: "禁止做某事(forbid)" },
    { word: "forgive doing sth.", meaning: "原谅做某事(forgive)" },
    { word: "give up doing sth.", meaning: "放弃做某事(give)" },
    { word: "argue sb. into doing sth.", meaning: "说服某人做某事(argue)" },
    { word: "cheat sb. into doing sth.", meaning: "欺骗某人做某事(cheat)" },
    { word: "fool sb. into doing sth.", meaning: "愚弄某人做某事(fool)" },
    { word: "force sb. into doing sth.", meaning: "强迫某人做某事(force)" },
    { word: "frighten sb. into doing sth.", meaning: "吓唬某人做某事(frighten)" },
    { word: "persuade sb. into doing sth.", meaning: "说服某人做某事(persuade)" },
    { word: "talk sb. into doing sth.", meaning: "劝说某人做某事(talk)" },
    { word: "terrify sb. into doing sth.", meaning: "恐吓某人做某事(terrify)" },
    { word: "accuse sb. of sth.", meaning: "指控某人某事(accuse)" },
    { word: "cheat sb. of sth.", meaning: "骗取某人某物(cheat)" },
    { word: "cure sb. of sth.", meaning: "治愈某人某病(cure)" },
    { word: "trick sb. into doing sth.", meaning: "哄骗某人做某事(trick)" },
    { word: "remind sb. of sth.", meaning: "使某人想起某事(remind)" },
    { word: "rid sb. of sth.", meaning: "使某人摆脱某物(rid)" },
    { word: "rob sb. of sth.", meaning: "抢劫某人某物(rob)" },
    { word: "warn sb. of sth.", meaning: "警告某人某事(warn)" },
    { word: "inform sb. of sth.", meaning: "通知某人某事(inform)" },
    { word: "advise sb. to do sth.", meaning: "建议某人做某事(advise)" },
    { word: "allow sb. to do sth.", meaning: "允许某人做某事(allow)" },
    { word: "ask sb. to do sth.", meaning: "要求某人做某事(ask)" },
    { word: "beg sb. to do sth.", meaning: "请求某人做某事(beg)" },
    { word: "cause sb. to do sth.", meaning: "导致某人做某事(cause)" },
    { word: "drive sb. to do sth.", meaning: "驱使某人做某事(drive)" },
    { word: "elect sb. to do sth.", meaning: "选举某人做某事(elect)" },
    { word: "encourage sb.to do sth.", meaning: "鼓励某人做某事(encourage)" },
    { word: "expect sb.to do sth.", meaning: "期望某人做某事(expect)" },
    { word: "forbid sb.to do sth.", meaning: "禁止某人做某事(forbid)" },
    { word: "force sb.to do sth.", meaning: "强迫某人做某事(force)" },
    { word: "get sb.to do sth.", meaning: "让某人做某事(get)" },
    { word: "hate sb.to do sth.", meaning: "讨厌某人做某事(hate)" },
    { word: "help sb. do sth.", meaning: "帮助某人做某事(help)" },
    { word: "intend sb.to do sth.", meaning: "打算让某人做某事(intend)" },
    { word: "invite sb.to do sth.", meaning: "邀请某人做某事(invite)" },
    { word: "leave sb.to do sth.", meaning: "留下某人做某事(leave)" },
    { word: "like sb.to do sth.", meaning: "喜欢某人做某事(like)" },
    { word: "need sb.to do sth.", meaning: "需要某人做某事(need)" },
    { word: "order sb.to do sth.", meaning: "命令某人做某事(order)" },
    { word: "permit sb.to do sth.", meaning: "允许某人做某事(permit)" },
    { word: "persuade sb.to do sth.", meaning: "说服某人做某事(persuade)" },
    { word: "remind sb.to do sth.", meaning: "提醒某人做某事(remind)" },
    { word: "request sb.to do sth.", meaning: "请求某人做某事(request)" },
    { word: "teach sb.to do sth.", meaning: "教某人做某事(teach)" },
    { word: "trouble sb.to do sth.", meaning: "麻烦某人做某事(trouble)" },
    { word: "want sb.to do sth.", meaning: "想要某人做某事(want)" },
    { word: "warn sb.to do sth.", meaning: "警告某人做某事(warn)" },
    { word: "wish sb.to do sth.", meaning: "希望某人做某事(wish)" },
    { word: "begin to do sth.", meaning: "开始做某事(begin)" },
    { word: "fail to do sth.", meaning: "未能做某事(fail)" },
    { word: "forget to do sth.", meaning: "忘记去做某事(forget)" },
    { word: "happen to do sth.", meaning: "碰巧做某事(happen)" }
];
