export const wordList = [
    { word: "divide into", meaning: "把…分成…(divide)" },
    { word: "by the time", meaning: "到…为止(time)" },
    { word: "make sure", meaning: "确保(sure)" },
    { word: "have a hard time doing sth.", meaning: "做某事有困难(time)" },
    { word: "prepare for", meaning: "为…做准备(prepare)" },
    { word: "make great contributions to", meaning: "对…做出巨大贡献(contribution)" },
    { word: "had better (not) do sth.", meaning: "最好(不)做某事(better)" },
    { word: "avoid doing sth.", meaning: "避免做某事(avoid)" },
    { word: "be fond of doing sth.", meaning: "喜欢做某事(fond)" },
    { word: "in person", meaning: "亲自(person)" },
    { word: "stay awake", meaning: "保持清醒(awake)" },
    { word: "make room for", meaning: "为…腾出空间(room)" },
    { word: "give sb. some advice on", meaning: "给某人关于…的一些建议(advice)" },
    { word: "go to bed", meaning: "上床睡觉(bed)" },
    { word: "remember to do sth.", meaning: "记得要做某事(remember)" },
    { word: "remember doing sth.", meaning: "记得做过某事(remember)" },
    { word: "would you like to do sth.", meaning: "你愿意做某事吗(would)" },
    { word: "be so interested in", meaning: "对…如此感兴趣(interested)" },
    { word: "improve living standards", meaning: "提升生活水平(standard)" },
    { word: "take pride in", meaning: "以…为傲(pride)" },
    { word: "be proud of", meaning: "以…为傲(proud)" },
    { word: "enjoy doing sth.", meaning: "喜欢做某事(enjoy)" },
    { word: "make comments on", meaning: "就…做评价(comment)" },
    { word: "self-introduction", meaning: "自我介绍(introduction)" },
    { word: "take place", meaning: "发生(place)" },
    { word: "take the place of", meaning: "取代(place)" },
    { word: "get rid of", meaning: "去除，摆脱(rid)" },
    { word: "put into action", meaning: "付诸行动，把…付诸实践(action)" },
    { word: "put into practice", meaning: "付诸行动，把…付诸实践(practice)" },
    { word: "attract one's attention", meaning: "吸引某人的注意力(attract)" },
    { word: "draw one's attention", meaning: "吸引某人的注意力(draw)" },
    { word: "catch one's attention", meaning: "吸引某人的注意力(catch)" },
    { word: "pay attention to doing sth.", meaning: "注意做某事(attention)" },
    { word: "tend to do sth.", meaning: "往往会做某事(tend)" },
    { word: "achieve one's dream", meaning: "实现某人的梦想(achieve)" },
    { word: "make one's dream come true", meaning: "实现某人的梦想(come)" },
    { word: "out of", meaning: "出自，缺少，脱离(out)" },
    { word: "in addition to doing sth.", meaning: "除了做某事之外还有(addition)" },
    { word: "at all", meaning: "根本，究竟(all)" },
    { word: "a lack of", meaning: "缺乏(lack->n.)" },
    { word: "lacking in", meaning: "缺乏(lack->adj.)" },
    { word: "be caught in the rain", meaning: "淋雨(catch)" },
    { word: "much to one's surprise", meaning: "令某人非常惊讶的是(much)" },
    { word: "different kinds of", meaning: "不同种类的(kind)" },
    { word: "sing high praise for", meaning: "高度赞扬(praise)" },
    { word: "play an important role in", meaning: "在…中扮演重要角色(role)" },
    { word: "play an important part in", meaning: "在…方面起重要作用(part)" },
    { word: "devote oneself to doing sth.", meaning: "投身于做某事(devote)" },
    { word: "sb. be devoted to doing sth.", meaning: "某人投身于做某事(devoted)" },
    { word: "devotion to doing sth.", meaning: "对做某事的奉献(devotion)" },
    { word: "manage to do sth.", meaning: "设法做某事(manage)" },
    { word: "a variety of", meaning: "各种各样的(variety)" },
    { word: "be likely to do sth.", meaning: "很可能会做某事(likely to)" },
    { word: "it is likely that", meaning: "很可能…(likely that)" },
    { word: "whether or", meaning: "是…还是…(whether)" },
    { word: "blow away", meaning: "吹走，深深打动(blow)" },
    { word: "bring down", meaning: "降低，打倒(bring)" },
    { word: "keep in touch with", meaning: "与…保持联系(touch)" },
    { word: "one day", meaning: "总有一天(day)" },
    { word: "by all means", meaning: "当然，无论如何，用一切手段(all)" },
    { word: "by any means", meaning: "通过任何方式，无论如何(any)" },
    { word: "by no means", meaning: "决不，绝不(no)" },
    { word: "by means of", meaning: "通过/依靠…(方法)(means)" },
    { word: "be to blame for", meaning: "应受谴责，应负责任(blame)" },
    { word: "blame sb. for sth.", meaning: "因某事责怪某人(blame)" },
    { word: "blame sth. on sb.", meaning: "把某事怪到某人头上(blame)" },
    { word: "be different from", meaning: "与…不同(different)" },
    { word: "the same as", meaning: "与…相同(same)" },
    { word: "be similar to", meaning: "与…相似(similar)" },
    { word: "try one's best", meaning: "尽某人最大努力(try)" },
    { word: "make the best of", meaning: "尽力而为，充分利用(make)" },
    { word: "all the best", meaning: "万事如意，一切顺利(all)" },
    { word: "on condition that", meaning: "条件是(condition)" }
];